/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { collectExtraKeys as collectExtraKeys$ } from "../../lib/schemas.js";
import { AuthleteError } from "./authleteerror.js";

/**
 * Error response returned by the Authlete IdP server. Unlike the main API's
 *
 * @remarks
 * `resultCode`/`resultMessage` format, IdP errors carry a human-readable `error` message,
 * optionally accompanied by contextual fields (such as `organizationId` or `apiServerId`).
 * Request validation failures instead return an `errors` array of per-field messages.
 */
export type IdpErrorData = {
  /**
   * A human-readable error message.
   */
  error?: string | undefined;
  /**
   * Per-field validation error messages, present for request validation failures.
   */
  errors?: Array<string> | undefined;

  additionalProperties: { [k: string]: any };
};

/**
 * Error response returned by the Authlete IdP server. Unlike the main API's
 *
 * @remarks
 * `resultCode`/`resultMessage` format, IdP errors carry a human-readable `error` message,
 * optionally accompanied by contextual fields (such as `organizationId` or `apiServerId`).
 * Request validation failures instead return an `errors` array of per-field messages.
 */
export class IdpError extends AuthleteError {
  /**
   * A human-readable error message.
   */
  error?: string | undefined;
  /**
   * Per-field validation error messages, present for request validation failures.
   */
  errors?: Array<string> | undefined;
  additionalProperties: { [k: string]: any } = {};

  /** The original data that was passed to this error instance. */
  data$: IdpErrorData;

  constructor(
    err: IdpErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.errors != null) this.errors = err.errors;
    if (err.additionalProperties != null) {
      this.additionalProperties = err.additionalProperties;
    }

    this.name = "IdpError";
  }
}

/** @internal */
export const IdpError$inboundSchema: z.ZodType<
  IdpError,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    error: z.string().optional(),
    errors: z.array(z.string()).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .catchall(z.any()),
  "additionalProperties",
  false,
)
  .transform((v) => {
    return new IdpError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
