/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditGet } from "../funcs/auditGet.js";
import { auditGetTypes } from "../funcs/auditGetTypes.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Audit extends ClientSDK {
  /**
   * Get Audit Logs
   *
   * @remarks
   * Retrieve audit logs as a cursor-paginated list. Results can be filtered by time range, event type,
   * and organization.
   */
  async get(
    request?: operations.AuditEntriesGetIdpApiRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.AuditEntriesGetIdpApiResponse, { cursor: string }>
  > {
    return unwrapResultIterator(auditGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Audit Log Event Types
   *
   * @remarks
   * Returns the list of available audit log event types for this environment.
   *
   * Accessible with a user access token or an organization token that has the
   * `view_audit_log` permission (e.g. a token created with the `admin` or
   * `audit_reader` preset).
   *
   * This endpoint is hosted on the Authlete IdP server (`https://login.authlete.com`),
   * not on the regional API clusters.
   */
  async getTypes(
    options?: RequestOptions,
  ): Promise<Array<string>> {
    return unwrapAsync(auditGetTypes(
      this,
      options,
    ));
  }
}
