/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authorizationFail } from "../funcs/authorizationFail.js";
import { authorizationIssue } from "../funcs/authorizationIssue.js";
import { authorizationProcessRequest } from "../funcs/authorizationProcessRequest.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { AuthorizationManagement } from "./authorizationmanagement.js";

export class Authorization extends ClientSDK {
  private _management?: AuthorizationManagement;
  get management(): AuthorizationManagement {
    return (this._management ??= new AuthorizationManagement(this._options));
  }

  /**
   * Process Authorization Request
   *
   * @remarks
   * This API parses request parameters of an authorization request and returns necessary data for the authorization server
   * implementation to process the authorization request further.
   */
  async processRequest(
    request: operations.AuthAuthorizationApiRequest,
    options?: RequestOptions,
  ): Promise<models.AuthorizationResponse> {
    return unwrapAsync(authorizationProcessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Fail Authorization Request
   *
   * @remarks
   * This API generates a content of an error authorization response that the authorization server implementation
   * returns to the client application.
   */
  async fail(
    request: operations.AuthAuthorizationFailApiRequest,
    options?: RequestOptions,
  ): Promise<models.AuthorizationFailResponse> {
    return unwrapAsync(authorizationFail(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue Authorization Response
   *
   * @remarks
   * This API parses request parameters of an authorization request and returns necessary data for the
   * authorization server implementation to process the authorization request further.
   */
  async issue(
    request: operations.AuthAuthorizationIssueApiRequest,
    options?: RequestOptions,
  ): Promise<models.AuthorizationIssueResponse> {
    return unwrapAsync(authorizationIssue(
      this,
      request,
      options,
    ));
  }
}
