/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backChannelLogoutBackchannelLogoutTokenApi } from "../funcs/backChannelLogoutBackchannelLogoutTokenApi.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BackChannelLogout extends ClientSDK {
  /**
   * Backchannel Logout Token Issuing
   *
   * @remarks
   * The `/backchannel/logout/token` API issues a logout token for a client application
   * in the context of [OpenID Connect Back-Channel Logout 1.0](https://openid.net/specs/openid-connect-backchannel-1_0.html).
   */
  async backchannelLogoutTokenApi(
    request: operations.BackchannelLogoutTokenApiRequest,
    options?: RequestOptions,
  ): Promise<operations.BackchannelLogoutTokenApiResponse> {
    return unwrapAsync(backChannelLogoutBackchannelLogoutTokenApi(
      this,
      request,
      options,
    ));
  }
}
