/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cibaComplete } from "../funcs/cibaComplete.js";
import { cibaFail } from "../funcs/cibaFail.js";
import { cibaIssue } from "../funcs/cibaIssue.js";
import { cibaProcessAuthentication } from "../funcs/cibaProcessAuthentication.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ciba extends ClientSDK {
  /**
   * Process Backchannel Authentication Request
   *
   * @remarks
   * This API parses request parameters of a [backchannel authentication request](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_request)
   * and returns necessary data for the authorization server implementation to process the backchannel
   * authentication request further.
   */
  async processAuthentication(
    request: operations.BackchannelAuthenticationApiRequest,
    options?: RequestOptions,
  ): Promise<models.BackchannelAuthenticationResponse> {
    return unwrapAsync(cibaProcessAuthentication(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue Backchannel Authentication Response
   *
   * @remarks
   * This API prepares JSON that contains an `auth_req_id`. The JSON should be used as the response body
   * of the response which is returned to the client from the [backchannel authentication endpoint](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_backchannel_endpoint)
   */
  async issue(
    request: operations.BackchannelAuthenticationIssueApiRequest,
    options?: RequestOptions,
  ): Promise<models.BackchannelAuthenticationIssueResponse> {
    return unwrapAsync(cibaIssue(
      this,
      request,
      options,
    ));
  }

  /**
   * Fail Backchannel Authentication Request
   *
   * @remarks
   * The API prepares JSON that contains an error. The JSON should be used as the response body of the
   * response which is returned to the client from the [backchannel authentication endpoint](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_backchannel_endpoint).
   */
  async fail(
    request: operations.BackchannelAuthenticationFailApiRequest,
    options?: RequestOptions,
  ): Promise<models.BackchannelAuthenticationFailResponse> {
    return unwrapAsync(cibaFail(
      this,
      request,
      options,
    ));
  }

  /**
   * Complete Backchannel Authentication
   *
   * @remarks
   * This API returns information about what action the authorization server should take after it receives
   * the result of end-user's decision about whether the end-user has approved or rejected a client application's
   * request on the authentication device.
   */
  async complete(
    request: operations.BackchannelAuthenticationCompleteApiRequest,
    options?: RequestOptions,
  ): Promise<models.BackchannelAuthenticationCompleteResponse> {
    return unwrapAsync(cibaComplete(
      this,
      request,
      options,
    ));
  }
}
