/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientManagementDeleteAuthorizations } from "../funcs/clientManagementDeleteAuthorizations.js";
import { clientManagementDeleteClientGrantedScopes } from "../funcs/clientManagementDeleteClientGrantedScopes.js";
import { clientManagementDeleteClientTokens } from "../funcs/clientManagementDeleteClientTokens.js";
import { clientManagementDeleteClientTokensByPost } from "../funcs/clientManagementDeleteClientTokensByPost.js";
import { clientManagementDeleteGrantedScopes } from "../funcs/clientManagementDeleteGrantedScopes.js";
import { clientManagementDeleteRequestableScopes } from "../funcs/clientManagementDeleteRequestableScopes.js";
import { clientManagementGetAuthorizedApplications } from "../funcs/clientManagementGetAuthorizedApplications.js";
import { clientManagementGetAuthorizedApplicationsByPost } from "../funcs/clientManagementGetAuthorizedApplicationsByPost.js";
import { clientManagementGetClientGrantedScopes } from "../funcs/clientManagementGetClientGrantedScopes.js";
import { clientManagementGetClientGrantedScopesByPost } from "../funcs/clientManagementGetClientGrantedScopesByPost.js";
import { clientManagementGetGrantedScopes } from "../funcs/clientManagementGetGrantedScopes.js";
import { clientManagementGetRequestableScopes } from "../funcs/clientManagementGetRequestableScopes.js";
import { clientManagementListAuthorizations } from "../funcs/clientManagementListAuthorizations.js";
import { clientManagementRefreshSecret } from "../funcs/clientManagementRefreshSecret.js";
import { clientManagementUpdateAuthorizations } from "../funcs/clientManagementUpdateAuthorizations.js";
import { clientManagementUpdateLockFlag } from "../funcs/clientManagementUpdateLockFlag.js";
import { clientManagementUpdateRequestableScopes } from "../funcs/clientManagementUpdateRequestableScopes.js";
import { clientManagementUpdateRequestableScopesByPost } from "../funcs/clientManagementUpdateRequestableScopesByPost.js";
import { clientManagementUpdateSecret } from "../funcs/clientManagementUpdateSecret.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ClientManagement extends ClientSDK {
  /**
   * Update Client Lock
   *
   * @remarks
   * Lock and unlock a client
   */
  async updateLockFlag(
    request: operations.ClientFlagUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientFlagUpdateApiResponse> {
    return unwrapAsync(clientManagementUpdateLockFlag(
      this,
      request,
      options,
    ));
  }

  /**
   * Rotate Client Secret
   *
   * @remarks
   * Refresh the client secret of a client. A new value of the client secret will be generated by the
   * Authlete server.
   *
   * If you want to specify a new value, use `/api/client/secret/update` API.
   */
  async refreshSecret(
    request: operations.ClientSecretRefreshApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientSecretRefreshApiResponse> {
    return unwrapAsync(clientManagementRefreshSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Client Secret
   *
   * @remarks
   * Update the client secret of a client.
   *
   * If you want to have the Authlete server generate a new value of the client secret, use `/api/client/secret/refresh`
   * API.
   */
  async updateSecret(
    request: operations.ClientSecretUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientSecretUpdateApiResponse> {
    return unwrapAsync(clientManagementUpdateSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Authorized Applications
   *
   * @remarks
   * Get a list of client applications that an end-user has authorized.
   *
   * The subject parameter is required and can be provided as a query parameter.
   */
  async getAuthorizedApplications(
    request: operations.ClientAuthorizationGetListApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationGetListApiResponse> {
    return unwrapAsync(clientManagementGetAuthorizedApplications(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Authorized Applications
   *
   * @remarks
   * Get a list of client applications that an end-user has authorized.
   *
   * The subject parameter is required.
   */
  async getAuthorizedApplicationsByPost(
    request: operations.ClientAuthorizationGetListApiPostRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationGetListApiPostResponse> {
    return unwrapAsync(clientManagementGetAuthorizedApplicationsByPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Authorized Applications (by Subject)
   *
   * @remarks
   * Get a list of client applications that an end-user has authorized.
   * In this variant, the subject is provided in the path.
   */
  async listAuthorizations(
    request: operations.ClientAuthorizationGetListBySubjectApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationGetListBySubjectApiResponse> {
    return unwrapAsync(clientManagementListAuthorizations(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Client Tokens
   *
   * @remarks
   * Update attributes of all existing access tokens given to a client application.
   */
  async updateAuthorizations(
    request: operations.ClientAuthorizationUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationUpdateApiResponse> {
    return unwrapAsync(clientManagementUpdateAuthorizations(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Client Tokens
   *
   * @remarks
   * Delete all existing access tokens issued to a client application by an end-user.
   *
   * The subject parameter is required and must be provided as a query parameter.
   */
  async deleteClientTokens(
    request: operations.ClientAuthorizationDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationDeleteApiResponse> {
    return unwrapAsync(clientManagementDeleteClientTokens(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Client Tokens
   *
   * @remarks
   * Delete all existing access tokens issued to a client application by an end-user.
   *
   * The subject parameter is required.
   */
  async deleteClientTokensByPost(
    request: operations.ClientAuthorizationDeleteApiPostRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationDeleteApiPostResponse> {
    return unwrapAsync(clientManagementDeleteClientTokensByPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Client Tokens (by Subject)
   *
   * @remarks
   * Delete all existing access tokens issued to a client application by an end-user.
   * In this variant, the subject is provided in the path.
   */
  async deleteAuthorizations(
    request: operations.ClientAuthorizationDeleteBySubjectApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientAuthorizationDeleteBySubjectApiResponse> {
    return unwrapAsync(clientManagementDeleteAuthorizations(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Granted Scopes
   *
   * @remarks
   * Get the set of scopes that a user has granted to a client application.
   */
  async getClientGrantedScopes(
    request: operations.ClientGrantedScopesGetApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientGrantedScopesGetApiResponse> {
    return unwrapAsync(clientManagementGetClientGrantedScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Granted Scopes
   *
   * @remarks
   * Get the set of scopes that a user has granted to a client application.
   *
   * The subject parameter is required.
   */
  async getClientGrantedScopesByPost(
    request: operations.ClientGrantedScopesGetApiPostRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientGrantedScopesGetApiPostResponse> {
    return unwrapAsync(clientManagementGetClientGrantedScopesByPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Granted Scopes (by Subject)
   *
   * @remarks
   * Get the set of scopes that a user has granted to a client application.
   * In this variant, the subject is provided in the path.
   */
  async getGrantedScopes(
    request: operations.ClientGrantedScopesGetBySubjectApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientGrantedScopesGetBySubjectApiResponse> {
    return unwrapAsync(clientManagementGetGrantedScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Granted Scopes
   *
   * @remarks
   * Delete the set of scopes that an end-user has granted to a client application.
   *
   * Even if records about granted scopes are deleted by calling this API, existing access tokens are
   * not deleted and scopes of existing access tokens are not changed.
   * The subject parameter is required and must be provided as a query parameter.
   */
  async deleteClientGrantedScopes(
    request: operations.ClientGrantedScopesDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientGrantedScopesDeleteApiResponse> {
    return unwrapAsync(clientManagementDeleteClientGrantedScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Granted Scopes (by Subject)
   *
   * @remarks
   * Delete the set of scopes that an end-user has granted to a client application.
   * In this variant, the subject is provided in the path.
   */
  async deleteGrantedScopes(
    request: operations.ClientGrantedScopesDeleteBySubjectApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientGrantedScopesDeleteBySubjectApiResponse> {
    return unwrapAsync(clientManagementDeleteGrantedScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Requestable Scopes
   *
   * @remarks
   * Get the requestable scopes per client
   */
  async getRequestableScopes(
    request: operations.ClientExtensionRequestablesScopesGetApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientExtensionRequestablesScopesGetApiResponse> {
    return unwrapAsync(clientManagementGetRequestableScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Requestable Scopes
   *
   * @remarks
   * Update requestable scopes of a client
   */
  async updateRequestableScopesByPost(
    request: operations.ClientExtensionRequestablesScopesUpdateApiPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ClientExtensionRequestablesScopesUpdateApiPostResponse
  > {
    return unwrapAsync(clientManagementUpdateRequestableScopesByPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Requestable Scopes
   *
   * @remarks
   * Update requestable scopes of a client
   */
  async updateRequestableScopes(
    request: operations.ClientExtensionRequestablesScopesUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ClientExtensionRequestablesScopesUpdateApiResponse> {
    return unwrapAsync(clientManagementUpdateRequestableScopes(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Requestable Scopes
   *
   * @remarks
   * Delete requestable scopes of a client
   */
  async deleteRequestableScopes(
    request: operations.ClientExtensionRequestablesScopesDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ClientExtensionRequestablesScopesDeleteApiResponse | undefined
  > {
    return unwrapAsync(clientManagementDeleteRequestableScopes(
      this,
      request,
      options,
    ));
  }
}
