/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deviceFlowAuthorization } from "../funcs/deviceFlowAuthorization.js";
import { deviceFlowComplete } from "../funcs/deviceFlowComplete.js";
import { deviceFlowVerification } from "../funcs/deviceFlowVerification.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DeviceFlow extends ClientSDK {
  /**
   * Process Device Authorization Request
   *
   * @remarks
   * This API parses request parameters of a [device authorization request](https://datatracker.ietf.org/doc/html/rfc8628#section-3.1)
   * and returns necessary data for the authorization server implementation to process the device authorization
   * request further.
   */
  async authorization(
    request: operations.DeviceAuthorizationApiRequest,
    options?: RequestOptions,
  ): Promise<models.DeviceAuthorizationResponse> {
    return unwrapAsync(deviceFlowAuthorization(
      this,
      request,
      options,
    ));
  }

  /**
   * Process Device Verification Request
   *
   * @remarks
   * The API returns information associated with a user code.
   */
  async verification(
    request: operations.DeviceVerificationApiRequest,
    options?: RequestOptions,
  ): Promise<models.DeviceVerificationResponse> {
    return unwrapAsync(deviceFlowVerification(
      this,
      request,
      options,
    ));
  }

  /**
   * Complete Device Authorization
   *
   * @remarks
   * This API returns information about what action the authorization server should take after it receives
   * the result of end-user's decision about whether the end-user has approved or rejected a client
   * application's request.
   */
  async complete(
    request: operations.DeviceCompleteApiRequest,
    options?: RequestOptions,
  ): Promise<models.DeviceCompleteResponse> {
    return unwrapAsync(deviceFlowComplete(
      this,
      request,
      options,
    ));
  }
}
