/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dynamicClientRegistrationDelete } from "../funcs/dynamicClientRegistrationDelete.js";
import { dynamicClientRegistrationGet } from "../funcs/dynamicClientRegistrationGet.js";
import { dynamicClientRegistrationRegister } from "../funcs/dynamicClientRegistrationRegister.js";
import { dynamicClientRegistrationUpdate } from "../funcs/dynamicClientRegistrationUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DynamicClientRegistration extends ClientSDK {
  /**
   * Register Client
   *
   * @remarks
   * Register a client. This API is supposed to be used to implement a client registration endpoint that
   * complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591) (OAuth 2.0 Dynamic Client
   * Registration Protocol).
   */
  async register(
    request: operations.ClientRegistrationApiRequest,
    options?: RequestOptions,
  ): Promise<models.ClientRegistrationResponse> {
    return unwrapAsync(dynamicClientRegistrationRegister(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Client
   *
   * @remarks
   * Get a dynamically registered client. This API is supposed to be used to implement a client registration
   * management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
   * (OAuth 2.0 Dynamic Registration Management).
   */
  async get(
    request: operations.ClientRegistrationGetApiRequest,
    options?: RequestOptions,
  ): Promise<models.ClientRegistrationResponse> {
    return unwrapAsync(dynamicClientRegistrationGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Client
   *
   * @remarks
   * Update a dynamically registered client. This API is supposed to be used to implement a client
   * registration management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
   * (OAuth 2.0 Dynamic Registration Management).
   */
  async update(
    request: operations.ClientRegistrationUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<models.ClientRegistrationResponse> {
    return unwrapAsync(dynamicClientRegistrationUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Client
   *
   * @remarks
   * Delete a dynamically registered client. This API is supposed to be used to implement a client
   * registration management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
   * (OAuth 2.0 Dynamic Registration Management).
   */
  async delete(
    request: operations.ClientRegistrationDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<models.ClientRegistrationResponse> {
    return unwrapAsync(dynamicClientRegistrationDelete(
      this,
      request,
      options,
    ));
  }
}
