/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { introspectionProcess } from "../funcs/introspectionProcess.js";
import { introspectionStandardProcess } from "../funcs/introspectionStandardProcess.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Introspection extends ClientSDK {
  /**
   * Process Introspection Request
   *
   * @remarks
   * This API gathers information about an access token.
   */
  async process(
    request: operations.AuthIntrospectionApiRequest,
    options?: RequestOptions,
  ): Promise<models.IntrospectionResponse> {
    return unwrapAsync(introspectionProcess(
      this,
      request,
      options,
    ));
  }

  /**
   * Process OAuth 2.0 Introspection Request
   *
   * @remarks
   * This API exists to help your authorization server provide its own introspection API which complies
   * with [RFC 7662](https://tools.ietf.org/html/rfc7662) (OAuth 2.0 Token Introspection).
   */
  async standardProcess(
    request: operations.AuthIntrospectionStandardApiRequest,
    options?: RequestOptions,
  ): Promise<models.StandardIntrospectionResponse> {
    return unwrapAsync(introspectionStandardProcess(
      this,
      request,
      options,
    ));
  }
}
