/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { joseObjectJoseVerifyApi } from "../funcs/joseObjectJoseVerifyApi.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class JoseObject extends ClientSDK {
  /**
   * Verify JOSE
   *
   * @remarks
   * This API verifies a JOSE object.
   */
  async joseVerifyApi(
    request: operations.JoseVerifyApiRequest,
    options?: RequestOptions,
  ): Promise<operations.JoseVerifyApiResponse> {
    return unwrapAsync(joseObjectJoseVerifyApi(
      this,
      request,
      options,
    ));
  }
}
