/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nativeSsoLogout } from "../funcs/nativeSsoLogout.js";
import { nativeSsoProcess } from "../funcs/nativeSsoProcess.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NativeSso extends ClientSDK {
  /**
   * Native SSO Processing
   *
   * @remarks
   * This API should be called by the implementation of a token endpoint to generate the ID token and
   * token response that comply with [OpenID Connect Native SSO for Mobile Apps 1.0](https://openid.net/specs/openid-connect-native-sso-1_0.html)
   * (Native SSO) when Authlete’s `/auth/token` response indicates `action = NATIVE_SSO` (after you validate
   * the session id and verify or generate the device secret as required by the flow). The token endpoint
   * implementation should retrieve the value of `action` from the response and take the following steps
   * according to the value.
   */
  async process(
    request: operations.NativeSsoApiRequest,
    options?: RequestOptions,
  ): Promise<models.NativeSsoResponse> {
    return unwrapAsync(nativeSsoProcess(
      this,
      request,
      options,
    ));
  }

  /**
   * Native SSO Logout Processing
   *
   * @remarks
   * The `/nativesso/logout` API is supposed to be used to support the concept of "logout from all applications"
   * in the context of [OpenID Connect Native SSO for Mobile Apps 1.0](https://openid.net/specs/openid-connect-native-sso-1_0.html)
   * (Native SSO). This is accomplished by deleting access/refresh token records associated with the
   * specified session ID. In Authlete's implementation, access/refresh token records can be associated
   * with a session ID only through the mechanism introduced by Native SSO.
   */
  async logout(
    request: operations.NativeSsoLogoutApiRequest,
    options?: RequestOptions,
  ): Promise<models.NativeSsoLogoutResponse> {
    return unwrapAsync(nativeSsoLogout(
      this,
      request,
      options,
    ));
  }
}
