/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { revocationProcess } from "../funcs/revocationProcess.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Revocation extends ClientSDK {
  /**
   * Process Revocation Request
   *
   * @remarks
   * This API revokes access tokens and refresh tokens.
   */
  async process(
    request: operations.AuthRevocationApiRequest,
    options?: RequestOptions,
  ): Promise<models.RevocationResponse> {
    return unwrapAsync(revocationProcess(
      this,
      request,
      options,
    ));
  }
}
