/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serviceCreate } from "../funcs/serviceCreate.js";
import { serviceDelete } from "../funcs/serviceDelete.js";
import { serviceGet } from "../funcs/serviceGet.js";
import { serviceGetConfiguration } from "../funcs/serviceGetConfiguration.js";
import { serviceList } from "../funcs/serviceList.js";
import { serviceRemove } from "../funcs/serviceRemove.js";
import { serviceUpdate } from "../funcs/serviceUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Service extends ClientSDK {
  /**
   * Get Service
   *
   * @remarks
   * Get a service.
   *
   * If the access token can only view or modify clients underneath this service, but does not
   * have access to view this service directly, a limited view of the service will be returned.
   */
  async get(
    request: operations.ServiceGetApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ServiceGetApiResponse> {
    return unwrapAsync(serviceGet(
      this,
      request,
      options,
    ));
  }

  /**
   * List Services
   *
   * @remarks
   * Get a list of services.
   *
   * If the access token can only view or modify clients underneath a service, but does not
   * have access to view that service directly, a limited view of the service will be returned.
   * Otherwise, all properties of the service are returned.
   *
   * If the access token is an administrative token, this returns a list of all services on the Authlete instance.
   * Otherwise, all services that the access token can view, even in a limited fashion, are returned.
   */
  async list(
    request?: operations.ServiceGetListApiRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ServiceGetListApiResponse> {
    return unwrapAsync(serviceList(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Service
   *
   * @remarks
   * Update a service.
   */
  async update(
    request: operations.ServiceUpdateApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ServiceUpdateApiResponse> {
    return unwrapAsync(serviceUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Service ⚡
   *
   * @remarks
   * Delete a service.
   */
  async delete(
    request: operations.ServiceDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ServiceDeleteApiResponse | undefined> {
    return unwrapAsync(serviceDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Service (IDP)
   *
   * @remarks
   * Create a new service on the API server, belonging to the specified organization.
   * A service can be created with an organization token or by a user with the CREATE_SERVICE role.
   *
   * This endpoint is hosted on the Authlete IdP server (`https://login.authlete.com`),
   * not on the regional API clusters.
   */
  async create(
    request: models.ServiceCreateIdpRequest,
    options?: RequestOptions,
  ): Promise<models.Service> {
    return unwrapAsync(serviceCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Service (IDP) ⚡
   *
   * @remarks
   * Delete a service from the API server.
   * A service can be deleted with an organization token or by a user with the MODIFY_SERVICE role.
   *
   * This endpoint is hosted on the Authlete IdP server (`https://login.authlete.com`),
   * not on the regional API clusters.
   */
  async remove(
    request: models.ServiceRemoveIdpRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(serviceRemove(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Service Configuration
   *
   * @remarks
   * This API gathers configuration information about a service.
   *
   * This API is supposed to be called from within the implementation of the configuration endpoint of
   * the service where the service that supports OpenID Connect and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html)
   * must expose its configuration information in a JSON format. Details about the format are described
   * in "[3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)"
   * in OpenID Connect Discovery 1.0.
   */
  async getConfiguration(
    request: operations.ServiceConfigurationApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ServiceConfigurationApiResponse> {
    return unwrapAsync(serviceGetConfiguration(
      this,
      request,
      options,
    ));
  }
}
