/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokenFail } from "../funcs/tokenFail.js";
import { tokenIssue } from "../funcs/tokenIssue.js";
import { tokenProcess } from "../funcs/tokenProcess.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { TokenManagement } from "./tokenmanagement.js";

export class Token extends ClientSDK {
  private _management?: TokenManagement;
  get management(): TokenManagement {
    return (this._management ??= new TokenManagement(this._options));
  }

  /**
   * Process Token Request
   *
   * @remarks
   * This API parses request parameters of an authorization request and returns necessary data for the
   * authorization server implementation to process the authorization request further.
   */
  async process(
    request: operations.AuthTokenApiRequest,
    options?: RequestOptions,
  ): Promise<models.TokenResponse> {
    return unwrapAsync(tokenProcess(
      this,
      request,
      options,
    ));
  }

  /**
   * Fail Token Request
   *
   * @remarks
   * This API generates a content of an error token response that the authorization server implementation
   * returns to the client application.
   */
  async fail(
    request: operations.AuthTokenFailApiRequest,
    options?: RequestOptions,
  ): Promise<models.TokenFailResponse> {
    return unwrapAsync(tokenFail(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue Token Response
   *
   * @remarks
   * This API generates a content of a successful token response that the authorization server implementation
   * returns to the client application.
   */
  async issue(
    request: operations.AuthTokenIssueApiRequest,
    options?: RequestOptions,
  ): Promise<models.TokenIssueResponse> {
    return unwrapAsync(tokenIssue(
      this,
      request,
      options,
    ));
  }
}
