/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userinfoIssue } from "../funcs/userinfoIssue.js";
import { userinfoProcess } from "../funcs/userinfoProcess.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Userinfo extends ClientSDK {
  /**
   * Process UserInfo Request
   *
   * @remarks
   * This API gathers information about a user.
   */
  async process(
    request: operations.AuthUserinfoApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthUserinfoApiResponse> {
    return unwrapAsync(userinfoProcess(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue UserInfo Response
   *
   * @remarks
   * This API generates an ID token.
   */
  async issue(
    request: operations.AuthUserinfoIssueApiRequest,
    options?: RequestOptions,
  ): Promise<operations.AuthUserinfoIssueApiResponse> {
    return unwrapAsync(userinfoIssue(
      this,
      request,
      options,
    ));
  }
}
