/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * IDP Server
 */
export const AuditEntriesGetIdpApiServerIdp = "idp";

export const AuditEntriesGetIdpApiServerList = {
  [AuditEntriesGetIdpApiServerIdp]: "https://login.authlete.com",
};

export type AuditEntriesGetIdpApiRequest = {
  /**
   * Return logs after this timestamp (ISO 8601).
   */
  after?: Date | undefined;
  /**
   * Return logs before this timestamp (ISO 8601).
   */
  before?: Date | undefined;
  /**
   * Filter by event type (e.g. `service.create`, `security.login`, `client.create`).
   *
   * @remarks
   * Can be specified multiple times. The set of available event types is environment-specific
   * and includes server-side types; retrieve the full list from the `/api/audit/types` endpoint.
   */
  types?: Array<string> | undefined;
  /**
   * The organization to retrieve audit logs for. Not required when authenticating with an
   *
   * @remarks
   * organization token — the token's own organization is used, and a differing value is
   * rejected. Required for user access tokens, unless the user is an Authlete administrator
   * (administrators may omit it to query across all organizations).
   */
  organizationId?: number | undefined;
  /**
   * The maximum number of entries to return per page. Values outside the allowed range are
   *
   * @remarks
   * clamped; the effective value is echoed back in the response.
   */
  limit?: number | undefined;
  /**
   * An opaque cursor returned as `nextCursor` by a previous response. When provided, it takes
   *
   * @remarks
   * precedence over the `before` parameter.
   */
  cursor?: string | undefined;
};

export type AuditEntriesGetIdpApiResponse = {
  result: models.AuditEntriesGetResponse;
};

/** @internal */
export type AuditEntriesGetIdpApiRequest$Outbound = {
  after?: string | undefined;
  before?: string | undefined;
  types?: Array<string> | undefined;
  organizationId?: number | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const AuditEntriesGetIdpApiRequest$outboundSchema: z.ZodType<
  AuditEntriesGetIdpApiRequest$Outbound,
  z.ZodTypeDef,
  AuditEntriesGetIdpApiRequest
> = z.object({
  after: z.date().transform(v => v.toISOString()).optional(),
  before: z.date().transform(v => v.toISOString()).optional(),
  types: z.array(z.string()).optional(),
  organizationId: z.number().int().optional(),
  limit: z.number().int().default(100),
  cursor: z.string().optional(),
});

export function auditEntriesGetIdpApiRequestToJSON(
  auditEntriesGetIdpApiRequest: AuditEntriesGetIdpApiRequest,
): string {
  return JSON.stringify(
    AuditEntriesGetIdpApiRequest$outboundSchema.parse(
      auditEntriesGetIdpApiRequest,
    ),
  );
}

/** @internal */
export const AuditEntriesGetIdpApiResponse$inboundSchema: z.ZodType<
  AuditEntriesGetIdpApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.AuditEntriesGetResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function auditEntriesGetIdpApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuditEntriesGetIdpApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEntriesGetIdpApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEntriesGetIdpApiResponse' from JSON`,
  );
}
