/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * IDP Server
 */
export const AuditTypesGetIdpApiServerIdp = "idp";

export const AuditTypesGetIdpApiServerList = {
  [AuditTypesGetIdpApiServerIdp]: "https://login.authlete.com",
};
