/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthUserinfoIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  userinfoIssueRequest: models.UserinfoIssueRequest;
};

export type AuthUserinfoIssueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.UserinfoIssueResponse;
};

/** @internal */
export type AuthUserinfoIssueApiRequest$Outbound = {
  serviceId: string;
  userinfo_issue_request: models.UserinfoIssueRequest$Outbound;
};

/** @internal */
export const AuthUserinfoIssueApiRequest$outboundSchema: z.ZodType<
  AuthUserinfoIssueApiRequest$Outbound,
  z.ZodTypeDef,
  AuthUserinfoIssueApiRequest
> = z.object({
  serviceId: z.string(),
  userinfoIssueRequest: models.UserinfoIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    userinfoIssueRequest: "userinfo_issue_request",
  });
});

export function authUserinfoIssueApiRequestToJSON(
  authUserinfoIssueApiRequest: AuthUserinfoIssueApiRequest,
): string {
  return JSON.stringify(
    AuthUserinfoIssueApiRequest$outboundSchema.parse(
      authUserinfoIssueApiRequest,
    ),
  );
}

/** @internal */
export const AuthUserinfoIssueApiResponse$inboundSchema: z.ZodType<
  AuthUserinfoIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.UserinfoIssueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authUserinfoIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthUserinfoIssueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthUserinfoIssueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthUserinfoIssueApiResponse' from JSON`,
  );
}
