/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AuthTokenDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The identifier of an existing access token. The identifier is the value of the access token
   *
   * @remarks
   * or the value of the hash of the access token.
   */
  accessTokenIdentifier: string;
};

export type AuthTokenDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type AuthTokenDeleteApiRequest$Outbound = {
  serviceId: string;
  accessTokenIdentifier: string;
};

/** @internal */
export const AuthTokenDeleteApiRequest$outboundSchema: z.ZodType<
  AuthTokenDeleteApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenDeleteApiRequest
> = z.object({
  serviceId: z.string(),
  accessTokenIdentifier: z.string(),
});

export function authTokenDeleteApiRequestToJSON(
  authTokenDeleteApiRequest: AuthTokenDeleteApiRequest,
): string {
  return JSON.stringify(
    AuthTokenDeleteApiRequest$outboundSchema.parse(authTokenDeleteApiRequest),
  );
}

/** @internal */
export const AuthTokenDeleteApiResponse$inboundSchema: z.ZodType<
  AuthTokenDeleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function authTokenDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenDeleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenDeleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenDeleteApiResponse' from JSON`,
  );
}
