/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenIssueRequest: models.TokenIssueRequest;
};

export type AuthTokenIssueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenIssueResponse;
};

/** @internal */
export type AuthTokenIssueApiRequest$Outbound = {
  serviceId: string;
  token_issue_request: models.TokenIssueRequest$Outbound;
};

/** @internal */
export const AuthTokenIssueApiRequest$outboundSchema: z.ZodType<
  AuthTokenIssueApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenIssueApiRequest
> = z.object({
  serviceId: z.string(),
  tokenIssueRequest: models.TokenIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenIssueRequest: "token_issue_request",
  });
});

export function authTokenIssueApiRequestToJSON(
  authTokenIssueApiRequest: AuthTokenIssueApiRequest,
): string {
  return JSON.stringify(
    AuthTokenIssueApiRequest$outboundSchema.parse(authTokenIssueApiRequest),
  );
}

/** @internal */
export const AuthTokenIssueApiResponse$inboundSchema: z.ZodType<
  AuthTokenIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenIssueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenIssueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenIssueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenIssueApiResponse' from JSON`,
  );
}
