/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenFailApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenFailRequest: models.TokenFailRequest;
};

export type AuthTokenFailApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenFailResponse;
};

/** @internal */
export type AuthTokenFailApiRequest$Outbound = {
  serviceId: string;
  token_fail_request: models.TokenFailRequest$Outbound;
};

/** @internal */
export const AuthTokenFailApiRequest$outboundSchema: z.ZodType<
  AuthTokenFailApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenFailApiRequest
> = z.object({
  serviceId: z.string(),
  tokenFailRequest: models.TokenFailRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenFailRequest: "token_fail_request",
  });
});

export function authTokenFailApiRequestToJSON(
  authTokenFailApiRequest: AuthTokenFailApiRequest,
): string {
  return JSON.stringify(
    AuthTokenFailApiRequest$outboundSchema.parse(authTokenFailApiRequest),
  );
}

/** @internal */
export const AuthTokenFailApiResponse$inboundSchema: z.ZodType<
  AuthTokenFailApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenFailResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenFailApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenFailApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenFailApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenFailApiResponse' from JSON`,
  );
}
