/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenRequest: models.TokenRequest;
};

export type AuthTokenApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenResponse;
};

/** @internal */
export type AuthTokenApiRequest$Outbound = {
  serviceId: string;
  token_request: models.TokenRequest$Outbound;
};

/** @internal */
export const AuthTokenApiRequest$outboundSchema: z.ZodType<
  AuthTokenApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenApiRequest
> = z.object({
  serviceId: z.string(),
  tokenRequest: models.TokenRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenRequest: "token_request",
  });
});

export function authTokenApiRequestToJSON(
  authTokenApiRequest: AuthTokenApiRequest,
): string {
  return JSON.stringify(
    AuthTokenApiRequest$outboundSchema.parse(authTokenApiRequest),
  );
}

/** @internal */
export const AuthTokenApiResponse$inboundSchema: z.ZodType<
  AuthTokenApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenApiResponse' from JSON`,
  );
}
