/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthRevocationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  revocationRequest: models.RevocationRequest;
};

export type AuthRevocationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.RevocationResponse;
};

/** @internal */
export type AuthRevocationApiRequest$Outbound = {
  serviceId: string;
  revocation_request: models.RevocationRequest$Outbound;
};

/** @internal */
export const AuthRevocationApiRequest$outboundSchema: z.ZodType<
  AuthRevocationApiRequest$Outbound,
  z.ZodTypeDef,
  AuthRevocationApiRequest
> = z.object({
  serviceId: z.string(),
  revocationRequest: models.RevocationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    revocationRequest: "revocation_request",
  });
});

export function authRevocationApiRequestToJSON(
  authRevocationApiRequest: AuthRevocationApiRequest,
): string {
  return JSON.stringify(
    AuthRevocationApiRequest$outboundSchema.parse(authRevocationApiRequest),
  );
}

/** @internal */
export const AuthRevocationApiResponse$inboundSchema: z.ZodType<
  AuthRevocationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.RevocationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authRevocationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthRevocationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthRevocationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthRevocationApiResponse' from JSON`,
  );
}
