/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthIntrospectionApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  introspectionRequest: models.IntrospectionRequest;
};

export type AuthIntrospectionApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.IntrospectionResponse;
};

/** @internal */
export type AuthIntrospectionApiRequest$Outbound = {
  serviceId: string;
  introspection_request: models.IntrospectionRequest$Outbound;
};

/** @internal */
export const AuthIntrospectionApiRequest$outboundSchema: z.ZodType<
  AuthIntrospectionApiRequest$Outbound,
  z.ZodTypeDef,
  AuthIntrospectionApiRequest
> = z.object({
  serviceId: z.string(),
  introspectionRequest: models.IntrospectionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    introspectionRequest: "introspection_request",
  });
});

export function authIntrospectionApiRequestToJSON(
  authIntrospectionApiRequest: AuthIntrospectionApiRequest,
): string {
  return JSON.stringify(
    AuthIntrospectionApiRequest$outboundSchema.parse(
      authIntrospectionApiRequest,
    ),
  );
}

/** @internal */
export const AuthIntrospectionApiResponse$inboundSchema: z.ZodType<
  AuthIntrospectionApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.IntrospectionResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authIntrospectionApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthIntrospectionApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthIntrospectionApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthIntrospectionApiResponse' from JSON`,
  );
}
