/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthorizationTicketInfoPostApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationTicketInfoRequest: models.AuthorizationTicketInfoRequest;
};

export type AuthorizationTicketInfoPostApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuthorizationTicketInfoResponse;
};

/** @internal */
export type AuthorizationTicketInfoPostApiRequest$Outbound = {
  serviceId: string;
  authorization_ticket_info_request:
    models.AuthorizationTicketInfoRequest$Outbound;
};

/** @internal */
export const AuthorizationTicketInfoPostApiRequest$outboundSchema: z.ZodType<
  AuthorizationTicketInfoPostApiRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationTicketInfoPostApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationTicketInfoRequest:
    models.AuthorizationTicketInfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationTicketInfoRequest: "authorization_ticket_info_request",
  });
});

export function authorizationTicketInfoPostApiRequestToJSON(
  authorizationTicketInfoPostApiRequest: AuthorizationTicketInfoPostApiRequest,
): string {
  return JSON.stringify(
    AuthorizationTicketInfoPostApiRequest$outboundSchema.parse(
      authorizationTicketInfoPostApiRequest,
    ),
  );
}

/** @internal */
export const AuthorizationTicketInfoPostApiResponse$inboundSchema: z.ZodType<
  AuthorizationTicketInfoPostApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AuthorizationTicketInfoResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authorizationTicketInfoPostApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizationTicketInfoPostApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuthorizationTicketInfoPostApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizationTicketInfoPostApiResponse' from JSON`,
  );
}
