/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthAuthorizationFailApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationFailRequest: models.AuthorizationFailRequest;
};

export type AuthAuthorizationFailApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuthorizationFailResponse;
};

/** @internal */
export type AuthAuthorizationFailApiRequest$Outbound = {
  serviceId: string;
  authorization_fail_request: models.AuthorizationFailRequest$Outbound;
};

/** @internal */
export const AuthAuthorizationFailApiRequest$outboundSchema: z.ZodType<
  AuthAuthorizationFailApiRequest$Outbound,
  z.ZodTypeDef,
  AuthAuthorizationFailApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationFailRequest: models.AuthorizationFailRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationFailRequest: "authorization_fail_request",
  });
});

export function authAuthorizationFailApiRequestToJSON(
  authAuthorizationFailApiRequest: AuthAuthorizationFailApiRequest,
): string {
  return JSON.stringify(
    AuthAuthorizationFailApiRequest$outboundSchema.parse(
      authAuthorizationFailApiRequest,
    ),
  );
}

/** @internal */
export const AuthAuthorizationFailApiResponse$inboundSchema: z.ZodType<
  AuthAuthorizationFailApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AuthorizationFailResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authAuthorizationFailApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthAuthorizationFailApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthAuthorizationFailApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthAuthorizationFailApiResponse' from JSON`,
  );
}
