/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenUpdateRequest: models.TokenUpdateRequest;
};

export type AuthTokenUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenUpdateResponse;
};

/** @internal */
export type AuthTokenUpdateApiRequest$Outbound = {
  serviceId: string;
  token_update_request: models.TokenUpdateRequest$Outbound;
};

/** @internal */
export const AuthTokenUpdateApiRequest$outboundSchema: z.ZodType<
  AuthTokenUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  tokenUpdateRequest: models.TokenUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenUpdateRequest: "token_update_request",
  });
});

export function authTokenUpdateApiRequestToJSON(
  authTokenUpdateApiRequest: AuthTokenUpdateApiRequest,
): string {
  return JSON.stringify(
    AuthTokenUpdateApiRequest$outboundSchema.parse(authTokenUpdateApiRequest),
  );
}

/** @internal */
export const AuthTokenUpdateApiResponse$inboundSchema: z.ZodType<
  AuthTokenUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenUpdateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenUpdateApiResponse' from JSON`,
  );
}
