/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenCreateRequest: models.TokenCreateRequest;
};

export type AuthTokenCreateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenCreateResponse;
};

/** @internal */
export type AuthTokenCreateApiRequest$Outbound = {
  serviceId: string;
  token_create_request: models.TokenCreateRequest$Outbound;
};

/** @internal */
export const AuthTokenCreateApiRequest$outboundSchema: z.ZodType<
  AuthTokenCreateApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenCreateApiRequest
> = z.object({
  serviceId: z.string(),
  tokenCreateRequest: models.TokenCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenCreateRequest: "token_create_request",
  });
});

export function authTokenCreateApiRequestToJSON(
  authTokenCreateApiRequest: AuthTokenCreateApiRequest,
): string {
  return JSON.stringify(
    AuthTokenCreateApiRequest$outboundSchema.parse(authTokenCreateApiRequest),
  );
}

/** @internal */
export const AuthTokenCreateApiResponse$inboundSchema: z.ZodType<
  AuthTokenCreateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenCreateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenCreateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenCreateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenCreateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenCreateApiResponse' from JSON`,
  );
}
