/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthAuthorizationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationRequest: models.AuthorizationRequest;
};

export type AuthAuthorizationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuthorizationResponse;
};

/** @internal */
export type AuthAuthorizationApiRequest$Outbound = {
  serviceId: string;
  authorization_request: models.AuthorizationRequest$Outbound;
};

/** @internal */
export const AuthAuthorizationApiRequest$outboundSchema: z.ZodType<
  AuthAuthorizationApiRequest$Outbound,
  z.ZodTypeDef,
  AuthAuthorizationApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationRequest: models.AuthorizationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationRequest: "authorization_request",
  });
});

export function authAuthorizationApiRequestToJSON(
  authAuthorizationApiRequest: AuthAuthorizationApiRequest,
): string {
  return JSON.stringify(
    AuthAuthorizationApiRequest$outboundSchema.parse(
      authAuthorizationApiRequest,
    ),
  );
}

/** @internal */
export const AuthAuthorizationApiResponse$inboundSchema: z.ZodType<
  AuthAuthorizationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AuthorizationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authAuthorizationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthAuthorizationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthAuthorizationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthAuthorizationApiResponse' from JSON`,
  );
}
