/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthAuthorizationIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationIssueRequest: models.AuthorizationIssueRequest;
};

export type AuthAuthorizationIssueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuthorizationIssueResponse;
};

/** @internal */
export type AuthAuthorizationIssueApiRequest$Outbound = {
  serviceId: string;
  authorization_issue_request: models.AuthorizationIssueRequest$Outbound;
};

/** @internal */
export const AuthAuthorizationIssueApiRequest$outboundSchema: z.ZodType<
  AuthAuthorizationIssueApiRequest$Outbound,
  z.ZodTypeDef,
  AuthAuthorizationIssueApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationIssueRequest: models.AuthorizationIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationIssueRequest: "authorization_issue_request",
  });
});

export function authAuthorizationIssueApiRequestToJSON(
  authAuthorizationIssueApiRequest: AuthAuthorizationIssueApiRequest,
): string {
  return JSON.stringify(
    AuthAuthorizationIssueApiRequest$outboundSchema.parse(
      authAuthorizationIssueApiRequest,
    ),
  );
}

/** @internal */
export const AuthAuthorizationIssueApiResponse$inboundSchema: z.ZodType<
  AuthAuthorizationIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AuthorizationIssueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authAuthorizationIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthAuthorizationIssueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthAuthorizationIssueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthAuthorizationIssueApiResponse' from JSON`,
  );
}
