/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenRevokeApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenRevokeRequest: models.TokenRevokeRequest;
};

export type AuthTokenRevokeApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenRevokeResponse;
};

/** @internal */
export type AuthTokenRevokeApiRequest$Outbound = {
  serviceId: string;
  token_revoke_request: models.TokenRevokeRequest$Outbound;
};

/** @internal */
export const AuthTokenRevokeApiRequest$outboundSchema: z.ZodType<
  AuthTokenRevokeApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenRevokeApiRequest
> = z.object({
  serviceId: z.string(),
  tokenRevokeRequest: models.TokenRevokeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenRevokeRequest: "token_revoke_request",
  });
});

export function authTokenRevokeApiRequestToJSON(
  authTokenRevokeApiRequest: AuthTokenRevokeApiRequest,
): string {
  return JSON.stringify(
    AuthTokenRevokeApiRequest$outboundSchema.parse(authTokenRevokeApiRequest),
  );
}

/** @internal */
export const AuthTokenRevokeApiResponse$inboundSchema: z.ZodType<
  AuthTokenRevokeApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenRevokeResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenRevokeApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenRevokeApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenRevokeApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenRevokeApiResponse' from JSON`,
  );
}
