/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthUserinfoApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  userinfoRequest: models.UserinfoRequest;
};

export type AuthUserinfoApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.UserinfoResponse;
};

/** @internal */
export type AuthUserinfoApiRequest$Outbound = {
  serviceId: string;
  userinfo_request: models.UserinfoRequest$Outbound;
};

/** @internal */
export const AuthUserinfoApiRequest$outboundSchema: z.ZodType<
  AuthUserinfoApiRequest$Outbound,
  z.ZodTypeDef,
  AuthUserinfoApiRequest
> = z.object({
  serviceId: z.string(),
  userinfoRequest: models.UserinfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    userinfoRequest: "userinfo_request",
  });
});

export function authUserinfoApiRequestToJSON(
  authUserinfoApiRequest: AuthUserinfoApiRequest,
): string {
  return JSON.stringify(
    AuthUserinfoApiRequest$outboundSchema.parse(authUserinfoApiRequest),
  );
}

/** @internal */
export const AuthUserinfoApiResponse$inboundSchema: z.ZodType<
  AuthUserinfoApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.UserinfoResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authUserinfoApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthUserinfoApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthUserinfoApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthUserinfoApiResponse' from JSON`,
  );
}
