/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthTokenGetListApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * Client Identifier (client ID or client ID alias).
   *
   * @remarks
   */
  clientIdentifier?: string | undefined;
  /**
   * Unique user ID.
   *
   * @remarks
   */
  subject?: string | undefined;
  /**
   * Start index of search results (inclusive). The default value is 0.
   */
  start?: number | undefined;
  /**
   * End index of search results (exclusive). The default value is 5.
   *
   * @remarks
   */
  end?: number | undefined;
};

export type AuthTokenGetListApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TokenGetListResponse;
};

/** @internal */
export type AuthTokenGetListApiRequest$Outbound = {
  serviceId: string;
  clientIdentifier?: string | undefined;
  subject?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

/** @internal */
export const AuthTokenGetListApiRequest$outboundSchema: z.ZodType<
  AuthTokenGetListApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenGetListApiRequest
> = z.object({
  serviceId: z.string(),
  clientIdentifier: z.string().optional(),
  subject: z.string().optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
});

export function authTokenGetListApiRequestToJSON(
  authTokenGetListApiRequest: AuthTokenGetListApiRequest,
): string {
  return JSON.stringify(
    AuthTokenGetListApiRequest$outboundSchema.parse(authTokenGetListApiRequest),
  );
}

/** @internal */
export const AuthTokenGetListApiResponse$inboundSchema: z.ZodType<
  AuthTokenGetListApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TokenGetListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function authTokenGetListApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthTokenGetListApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthTokenGetListApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthTokenGetListApiResponse' from JSON`,
  );
}
