/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BackchannelAuthenticationCompleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelAuthenticationCompleteRequest:
    models.BackchannelAuthenticationCompleteRequest;
};

export type BackchannelAuthenticationCompleteApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BackchannelAuthenticationCompleteResponse;
};

/** @internal */
export type BackchannelAuthenticationCompleteApiRequest$Outbound = {
  serviceId: string;
  backchannel_authentication_complete_request:
    models.BackchannelAuthenticationCompleteRequest$Outbound;
};

/** @internal */
export const BackchannelAuthenticationCompleteApiRequest$outboundSchema:
  z.ZodType<
    BackchannelAuthenticationCompleteApiRequest$Outbound,
    z.ZodTypeDef,
    BackchannelAuthenticationCompleteApiRequest
  > = z.object({
    serviceId: z.string(),
    backchannelAuthenticationCompleteRequest:
      models.BackchannelAuthenticationCompleteRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      backchannelAuthenticationCompleteRequest:
        "backchannel_authentication_complete_request",
    });
  });

export function backchannelAuthenticationCompleteApiRequestToJSON(
  backchannelAuthenticationCompleteApiRequest:
    BackchannelAuthenticationCompleteApiRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationCompleteApiRequest$outboundSchema.parse(
      backchannelAuthenticationCompleteApiRequest,
    ),
  );
}

/** @internal */
export const BackchannelAuthenticationCompleteApiResponse$inboundSchema:
  z.ZodType<
    BackchannelAuthenticationCompleteApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: models.BackchannelAuthenticationCompleteResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function backchannelAuthenticationCompleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  BackchannelAuthenticationCompleteApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackchannelAuthenticationCompleteApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackchannelAuthenticationCompleteApiResponse' from JSON`,
  );
}
