/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BackchannelLogoutTokenApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelLogoutTokenRequest: models.BackchannelLogoutTokenRequest;
};

export type BackchannelLogoutTokenApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BackchannelLogoutTokenResponse;
};

/** @internal */
export type BackchannelLogoutTokenApiRequest$Outbound = {
  serviceId: string;
  backchannel_logout_token_request:
    models.BackchannelLogoutTokenRequest$Outbound;
};

/** @internal */
export const BackchannelLogoutTokenApiRequest$outboundSchema: z.ZodType<
  BackchannelLogoutTokenApiRequest$Outbound,
  z.ZodTypeDef,
  BackchannelLogoutTokenApiRequest
> = z.object({
  serviceId: z.string(),
  backchannelLogoutTokenRequest:
    models.BackchannelLogoutTokenRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    backchannelLogoutTokenRequest: "backchannel_logout_token_request",
  });
});

export function backchannelLogoutTokenApiRequestToJSON(
  backchannelLogoutTokenApiRequest: BackchannelLogoutTokenApiRequest,
): string {
  return JSON.stringify(
    BackchannelLogoutTokenApiRequest$outboundSchema.parse(
      backchannelLogoutTokenApiRequest,
    ),
  );
}

/** @internal */
export const BackchannelLogoutTokenApiResponse$inboundSchema: z.ZodType<
  BackchannelLogoutTokenApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.BackchannelLogoutTokenResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function backchannelLogoutTokenApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<BackchannelLogoutTokenApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackchannelLogoutTokenApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackchannelLogoutTokenApiResponse' from JSON`,
  );
}
