/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BackchannelAuthenticationIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelAuthenticationIssueRequest:
    models.BackchannelAuthenticationIssueRequest;
};

export type BackchannelAuthenticationIssueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BackchannelAuthenticationIssueResponse;
};

/** @internal */
export type BackchannelAuthenticationIssueApiRequest$Outbound = {
  serviceId: string;
  backchannel_authentication_issue_request:
    models.BackchannelAuthenticationIssueRequest$Outbound;
};

/** @internal */
export const BackchannelAuthenticationIssueApiRequest$outboundSchema: z.ZodType<
  BackchannelAuthenticationIssueApiRequest$Outbound,
  z.ZodTypeDef,
  BackchannelAuthenticationIssueApiRequest
> = z.object({
  serviceId: z.string(),
  backchannelAuthenticationIssueRequest:
    models.BackchannelAuthenticationIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    backchannelAuthenticationIssueRequest:
      "backchannel_authentication_issue_request",
  });
});

export function backchannelAuthenticationIssueApiRequestToJSON(
  backchannelAuthenticationIssueApiRequest:
    BackchannelAuthenticationIssueApiRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationIssueApiRequest$outboundSchema.parse(
      backchannelAuthenticationIssueApiRequest,
    ),
  );
}

/** @internal */
export const BackchannelAuthenticationIssueApiResponse$inboundSchema: z.ZodType<
  BackchannelAuthenticationIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.BackchannelAuthenticationIssueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function backchannelAuthenticationIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  BackchannelAuthenticationIssueApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackchannelAuthenticationIssueApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackchannelAuthenticationIssueApiResponse' from JSON`,
  );
}
