/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BackchannelAuthenticationFailApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelAuthenticationFailRequest:
    models.BackchannelAuthenticationFailRequest;
};

export type BackchannelAuthenticationFailApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BackchannelAuthenticationFailResponse;
};

/** @internal */
export type BackchannelAuthenticationFailApiRequest$Outbound = {
  serviceId: string;
  backchannel_authentication_fail_request:
    models.BackchannelAuthenticationFailRequest$Outbound;
};

/** @internal */
export const BackchannelAuthenticationFailApiRequest$outboundSchema: z.ZodType<
  BackchannelAuthenticationFailApiRequest$Outbound,
  z.ZodTypeDef,
  BackchannelAuthenticationFailApiRequest
> = z.object({
  serviceId: z.string(),
  backchannelAuthenticationFailRequest:
    models.BackchannelAuthenticationFailRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    backchannelAuthenticationFailRequest:
      "backchannel_authentication_fail_request",
  });
});

export function backchannelAuthenticationFailApiRequestToJSON(
  backchannelAuthenticationFailApiRequest:
    BackchannelAuthenticationFailApiRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationFailApiRequest$outboundSchema.parse(
      backchannelAuthenticationFailApiRequest,
    ),
  );
}

/** @internal */
export const BackchannelAuthenticationFailApiResponse$inboundSchema: z.ZodType<
  BackchannelAuthenticationFailApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.BackchannelAuthenticationFailResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function backchannelAuthenticationFailApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  BackchannelAuthenticationFailApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BackchannelAuthenticationFailApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BackchannelAuthenticationFailApiResponse' from JSON`,
  );
}
