/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BackchannelAuthenticationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelAuthenticationRequest: models.BackchannelAuthenticationRequest;
};

export type BackchannelAuthenticationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BackchannelAuthenticationResponse;
};

/** @internal */
export type BackchannelAuthenticationApiRequest$Outbound = {
  serviceId: string;
  backchannel_authentication_request:
    models.BackchannelAuthenticationRequest$Outbound;
};

/** @internal */
export const BackchannelAuthenticationApiRequest$outboundSchema: z.ZodType<
  BackchannelAuthenticationApiRequest$Outbound,
  z.ZodTypeDef,
  BackchannelAuthenticationApiRequest
> = z.object({
  serviceId: z.string(),
  backchannelAuthenticationRequest:
    models.BackchannelAuthenticationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    backchannelAuthenticationRequest: "backchannel_authentication_request",
  });
});

export function backchannelAuthenticationApiRequestToJSON(
  backchannelAuthenticationApiRequest: BackchannelAuthenticationApiRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationApiRequest$outboundSchema.parse(
      backchannelAuthenticationApiRequest,
    ),
  );
}

/** @internal */
export const BackchannelAuthenticationApiResponse$inboundSchema: z.ZodType<
  BackchannelAuthenticationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.BackchannelAuthenticationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function backchannelAuthenticationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<BackchannelAuthenticationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BackchannelAuthenticationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackchannelAuthenticationApiResponse' from JSON`,
  );
}
