/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationGetListApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  clientAuthorizationGetListRequest: models.ClientAuthorizationGetListRequest;
};

export type ClientAuthorizationGetListApiPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationGetListResponse;
};

/** @internal */
export type ClientAuthorizationGetListApiPostRequest$Outbound = {
  serviceId: string;
  client_authorization_get_list_request:
    models.ClientAuthorizationGetListRequest$Outbound;
};

/** @internal */
export const ClientAuthorizationGetListApiPostRequest$outboundSchema: z.ZodType<
  ClientAuthorizationGetListApiPostRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationGetListApiPostRequest
> = z.object({
  serviceId: z.string(),
  clientAuthorizationGetListRequest:
    models.ClientAuthorizationGetListRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    clientAuthorizationGetListRequest: "client_authorization_get_list_request",
  });
});

export function clientAuthorizationGetListApiPostRequestToJSON(
  clientAuthorizationGetListApiPostRequest:
    ClientAuthorizationGetListApiPostRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationGetListApiPostRequest$outboundSchema.parse(
      clientAuthorizationGetListApiPostRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationGetListApiPostResponse$inboundSchema: z.ZodType<
  ClientAuthorizationGetListApiPostResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationGetListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientAuthorizationGetListApiPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientAuthorizationGetListApiPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationGetListApiPostResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientAuthorizationGetListApiPostResponse' from JSON`,
  );
}
