/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ClientDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The client ID.
   */
  clientId: string;
};

export type ClientDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type ClientDeleteApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
};

/** @internal */
export const ClientDeleteApiRequest$outboundSchema: z.ZodType<
  ClientDeleteApiRequest$Outbound,
  z.ZodTypeDef,
  ClientDeleteApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
});

export function clientDeleteApiRequestToJSON(
  clientDeleteApiRequest: ClientDeleteApiRequest,
): string {
  return JSON.stringify(
    ClientDeleteApiRequest$outboundSchema.parse(clientDeleteApiRequest),
  );
}

/** @internal */
export const ClientDeleteApiResponse$inboundSchema: z.ZodType<
  ClientDeleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function clientDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientDeleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientDeleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientDeleteApiResponse' from JSON`,
  );
}
