/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   */
  clientId: string;
};

export type ClientGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Client;
};

/** @internal */
export type ClientGetApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
};

/** @internal */
export const ClientGetApiRequest$outboundSchema: z.ZodType<
  ClientGetApiRequest$Outbound,
  z.ZodTypeDef,
  ClientGetApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
});

export function clientGetApiRequestToJSON(
  clientGetApiRequest: ClientGetApiRequest,
): string {
  return JSON.stringify(
    ClientGetApiRequest$outboundSchema.parse(clientGetApiRequest),
  );
}

/** @internal */
export const ClientGetApiResponse$inboundSchema: z.ZodType<
  ClientGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Client$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGetApiResponse' from JSON`,
  );
}
