/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGrantedScopesDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientGrantedScopesDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientGrantedScopesDeleteResponse;
};

/** @internal */
export type ClientGrantedScopesDeleteApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientGrantedScopesDeleteApiRequest$outboundSchema: z.ZodType<
  ClientGrantedScopesDeleteApiRequest$Outbound,
  z.ZodTypeDef,
  ClientGrantedScopesDeleteApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  subject: z.string(),
});

export function clientGrantedScopesDeleteApiRequestToJSON(
  clientGrantedScopesDeleteApiRequest: ClientGrantedScopesDeleteApiRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesDeleteApiRequest$outboundSchema.parse(
      clientGrantedScopesDeleteApiRequest,
    ),
  );
}

/** @internal */
export const ClientGrantedScopesDeleteApiResponse$inboundSchema: z.ZodType<
  ClientGrantedScopesDeleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientGrantedScopesDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientGrantedScopesDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGrantedScopesDeleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientGrantedScopesDeleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGrantedScopesDeleteApiResponse' from JSON`,
  );
}
