/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGrantedScopesGetApiPostRequestBody = {
  /**
   * Unique user ID of an end-user.
   */
  subject: string;
};

export type ClientGrantedScopesGetApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  requestBody: ClientGrantedScopesGetApiPostRequestBody;
};

export type ClientGrantedScopesGetApiPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientGrantedScopesGetApiPostRequestBody$Outbound = {
  subject: string;
};

/** @internal */
export const ClientGrantedScopesGetApiPostRequestBody$outboundSchema: z.ZodType<
  ClientGrantedScopesGetApiPostRequestBody$Outbound,
  z.ZodTypeDef,
  ClientGrantedScopesGetApiPostRequestBody
> = z.object({
  subject: z.string(),
});

export function clientGrantedScopesGetApiPostRequestBodyToJSON(
  clientGrantedScopesGetApiPostRequestBody:
    ClientGrantedScopesGetApiPostRequestBody,
): string {
  return JSON.stringify(
    ClientGrantedScopesGetApiPostRequestBody$outboundSchema.parse(
      clientGrantedScopesGetApiPostRequestBody,
    ),
  );
}

/** @internal */
export type ClientGrantedScopesGetApiPostRequest$Outbound = {
  serviceId: string;
  clientId: string;
  RequestBody: ClientGrantedScopesGetApiPostRequestBody$Outbound;
};

/** @internal */
export const ClientGrantedScopesGetApiPostRequest$outboundSchema: z.ZodType<
  ClientGrantedScopesGetApiPostRequest$Outbound,
  z.ZodTypeDef,
  ClientGrantedScopesGetApiPostRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  requestBody: z.lazy(() =>
    ClientGrantedScopesGetApiPostRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientGrantedScopesGetApiPostRequestToJSON(
  clientGrantedScopesGetApiPostRequest: ClientGrantedScopesGetApiPostRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesGetApiPostRequest$outboundSchema.parse(
      clientGrantedScopesGetApiPostRequest,
    ),
  );
}

/** @internal */
export const ClientGrantedScopesGetApiPostResponse$inboundSchema: z.ZodType<
  ClientGrantedScopesGetApiPostResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientGrantedScopesGetApiPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGrantedScopesGetApiPostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientGrantedScopesGetApiPostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGrantedScopesGetApiPostResponse' from JSON`,
  );
}
