/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientAuthorizationDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientAuthorizationDeleteApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientAuthorizationDeleteApiRequest$outboundSchema: z.ZodType<
  ClientAuthorizationDeleteApiRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationDeleteApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  subject: z.string(),
});

export function clientAuthorizationDeleteApiRequestToJSON(
  clientAuthorizationDeleteApiRequest: ClientAuthorizationDeleteApiRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteApiRequest$outboundSchema.parse(
      clientAuthorizationDeleteApiRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationDeleteApiResponse$inboundSchema: z.ZodType<
  ClientAuthorizationDeleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientAuthorizationDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientAuthorizationDeleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationDeleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientAuthorizationDeleteApiResponse' from JSON`,
  );
}
