/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientSecretRefreshApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The client ID or the client ID alias of a client.
   *
   * @remarks
   */
  clientIdentifier: string;
};

export type ClientSecretRefreshApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientSecretRefreshResponse;
};

/** @internal */
export type ClientSecretRefreshApiRequest$Outbound = {
  serviceId: string;
  clientIdentifier: string;
};

/** @internal */
export const ClientSecretRefreshApiRequest$outboundSchema: z.ZodType<
  ClientSecretRefreshApiRequest$Outbound,
  z.ZodTypeDef,
  ClientSecretRefreshApiRequest
> = z.object({
  serviceId: z.string(),
  clientIdentifier: z.string(),
});

export function clientSecretRefreshApiRequestToJSON(
  clientSecretRefreshApiRequest: ClientSecretRefreshApiRequest,
): string {
  return JSON.stringify(
    ClientSecretRefreshApiRequest$outboundSchema.parse(
      clientSecretRefreshApiRequest,
    ),
  );
}

/** @internal */
export const ClientSecretRefreshApiResponse$inboundSchema: z.ZodType<
  ClientSecretRefreshApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientSecretRefreshResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientSecretRefreshApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientSecretRefreshApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientSecretRefreshApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientSecretRefreshApiResponse' from JSON`,
  );
}
