/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationGetListApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
  /**
   * Unique ID of a client developer.
   *
   * @remarks
   */
  developer?: string | undefined;
  /**
   * Start index of search results (inclusive). The default value is 0.
   */
  start?: number | undefined;
  /**
   * End index of search results (exclusive). The default value is 5.
   *
   * @remarks
   */
  end?: number | undefined;
};

export type ClientAuthorizationGetListApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationGetListResponse;
};

/** @internal */
export type ClientAuthorizationGetListApiRequest$Outbound = {
  serviceId: string;
  subject: string;
  developer?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

/** @internal */
export const ClientAuthorizationGetListApiRequest$outboundSchema: z.ZodType<
  ClientAuthorizationGetListApiRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationGetListApiRequest
> = z.object({
  serviceId: z.string(),
  subject: z.string(),
  developer: z.string().optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
});

export function clientAuthorizationGetListApiRequestToJSON(
  clientAuthorizationGetListApiRequest: ClientAuthorizationGetListApiRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationGetListApiRequest$outboundSchema.parse(
      clientAuthorizationGetListApiRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationGetListApiResponse$inboundSchema: z.ZodType<
  ClientAuthorizationGetListApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationGetListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientAuthorizationGetListApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientAuthorizationGetListApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationGetListApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientAuthorizationGetListApiResponse' from JSON`,
  );
}
