/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   */
  clientId: string;
  client?: models.ClientInput | undefined;
};

export type ClientUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Client;
};

/** @internal */
export type ClientUpdateApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  client?: models.ClientInput$Outbound | undefined;
};

/** @internal */
export const ClientUpdateApiRequest$outboundSchema: z.ZodType<
  ClientUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  client: models.ClientInput$outboundSchema.optional(),
});

export function clientUpdateApiRequestToJSON(
  clientUpdateApiRequest: ClientUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientUpdateApiRequest$outboundSchema.parse(clientUpdateApiRequest),
  );
}

/** @internal */
export const ClientUpdateApiResponse$inboundSchema: z.ZodType<
  ClientUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Client$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientUpdateApiResponse' from JSON`,
  );
}
