/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientFlagUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   */
  clientIdentifier: string;
  clientFlagUpdateRequest?: models.ClientFlagUpdateRequest | undefined;
};

export type ClientFlagUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientFlagUpdateResponse;
};

/** @internal */
export type ClientFlagUpdateApiRequest$Outbound = {
  serviceId: string;
  clientIdentifier: string;
  client_flag_update_request?:
    | models.ClientFlagUpdateRequest$Outbound
    | undefined;
};

/** @internal */
export const ClientFlagUpdateApiRequest$outboundSchema: z.ZodType<
  ClientFlagUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientFlagUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  clientIdentifier: z.string(),
  clientFlagUpdateRequest: models.ClientFlagUpdateRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    clientFlagUpdateRequest: "client_flag_update_request",
  });
});

export function clientFlagUpdateApiRequestToJSON(
  clientFlagUpdateApiRequest: ClientFlagUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientFlagUpdateApiRequest$outboundSchema.parse(clientFlagUpdateApiRequest),
  );
}

/** @internal */
export const ClientFlagUpdateApiResponse$inboundSchema: z.ZodType<
  ClientFlagUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientFlagUpdateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientFlagUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientFlagUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientFlagUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientFlagUpdateApiResponse' from JSON`,
  );
}
