/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationDeleteApiPostRequestBody = {
  /**
   * Unique user ID of an end-user.
   */
  subject: string;
};

export type ClientAuthorizationDeleteApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  requestBody: ClientAuthorizationDeleteApiPostRequestBody;
};

export type ClientAuthorizationDeleteApiPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientAuthorizationDeleteApiPostRequestBody$Outbound = {
  subject: string;
};

/** @internal */
export const ClientAuthorizationDeleteApiPostRequestBody$outboundSchema:
  z.ZodType<
    ClientAuthorizationDeleteApiPostRequestBody$Outbound,
    z.ZodTypeDef,
    ClientAuthorizationDeleteApiPostRequestBody
  > = z.object({
    subject: z.string(),
  });

export function clientAuthorizationDeleteApiPostRequestBodyToJSON(
  clientAuthorizationDeleteApiPostRequestBody:
    ClientAuthorizationDeleteApiPostRequestBody,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteApiPostRequestBody$outboundSchema.parse(
      clientAuthorizationDeleteApiPostRequestBody,
    ),
  );
}

/** @internal */
export type ClientAuthorizationDeleteApiPostRequest$Outbound = {
  serviceId: string;
  clientId: string;
  RequestBody: ClientAuthorizationDeleteApiPostRequestBody$Outbound;
};

/** @internal */
export const ClientAuthorizationDeleteApiPostRequest$outboundSchema: z.ZodType<
  ClientAuthorizationDeleteApiPostRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationDeleteApiPostRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  requestBody: z.lazy(() =>
    ClientAuthorizationDeleteApiPostRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientAuthorizationDeleteApiPostRequestToJSON(
  clientAuthorizationDeleteApiPostRequest:
    ClientAuthorizationDeleteApiPostRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteApiPostRequest$outboundSchema.parse(
      clientAuthorizationDeleteApiPostRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationDeleteApiPostResponse$inboundSchema: z.ZodType<
  ClientAuthorizationDeleteApiPostResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientAuthorizationDeleteApiPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientAuthorizationDeleteApiPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationDeleteApiPostResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientAuthorizationDeleteApiPostResponse' from JSON`,
  );
}
