/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGrantedScopesDeleteBySubjectApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientGrantedScopesDeleteBySubjectApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientGrantedScopesDeleteResponse;
};

/** @internal */
export type ClientGrantedScopesDeleteBySubjectApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientGrantedScopesDeleteBySubjectApiRequest$outboundSchema:
  z.ZodType<
    ClientGrantedScopesDeleteBySubjectApiRequest$Outbound,
    z.ZodTypeDef,
    ClientGrantedScopesDeleteBySubjectApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    subject: z.string(),
  });

export function clientGrantedScopesDeleteBySubjectApiRequestToJSON(
  clientGrantedScopesDeleteBySubjectApiRequest:
    ClientGrantedScopesDeleteBySubjectApiRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesDeleteBySubjectApiRequest$outboundSchema.parse(
      clientGrantedScopesDeleteBySubjectApiRequest,
    ),
  );
}

/** @internal */
export const ClientGrantedScopesDeleteBySubjectApiResponse$inboundSchema:
  z.ZodType<
    ClientGrantedScopesDeleteBySubjectApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: models.ClientGrantedScopesDeleteResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function clientGrantedScopesDeleteBySubjectApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientGrantedScopesDeleteBySubjectApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientGrantedScopesDeleteBySubjectApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientGrantedScopesDeleteBySubjectApiResponse' from JSON`,
  );
}
