/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientRegistrationGetApiRequestBody = {
  /**
   * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
   *
   * @remarks
   * (OAuth 2.0 Dynamic Client Registration Protocol).
   */
  json?: string | undefined;
  /**
   * The client registration access token. Used only for GET, UPDATE, and DELETE requests.
   *
   * @remarks
   */
  token: string;
  /**
   * The client's identifier. Used for GET, UPDATE, and DELETE requests
   *
   * @remarks
   */
  clientId: string;
};

export type ClientRegistrationGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  requestBody: ClientRegistrationGetApiRequestBody;
};

export type ClientRegistrationGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientRegistrationResponse;
};

/** @internal */
export type ClientRegistrationGetApiRequestBody$Outbound = {
  json?: string | undefined;
  token: string;
  clientId: string;
};

/** @internal */
export const ClientRegistrationGetApiRequestBody$outboundSchema: z.ZodType<
  ClientRegistrationGetApiRequestBody$Outbound,
  z.ZodTypeDef,
  ClientRegistrationGetApiRequestBody
> = z.object({
  json: z.string().optional(),
  token: z.string(),
  clientId: z.string(),
});

export function clientRegistrationGetApiRequestBodyToJSON(
  clientRegistrationGetApiRequestBody: ClientRegistrationGetApiRequestBody,
): string {
  return JSON.stringify(
    ClientRegistrationGetApiRequestBody$outboundSchema.parse(
      clientRegistrationGetApiRequestBody,
    ),
  );
}

/** @internal */
export type ClientRegistrationGetApiRequest$Outbound = {
  serviceId: string;
  RequestBody: ClientRegistrationGetApiRequestBody$Outbound;
};

/** @internal */
export const ClientRegistrationGetApiRequest$outboundSchema: z.ZodType<
  ClientRegistrationGetApiRequest$Outbound,
  z.ZodTypeDef,
  ClientRegistrationGetApiRequest
> = z.object({
  serviceId: z.string(),
  requestBody: z.lazy(() => ClientRegistrationGetApiRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientRegistrationGetApiRequestToJSON(
  clientRegistrationGetApiRequest: ClientRegistrationGetApiRequest,
): string {
  return JSON.stringify(
    ClientRegistrationGetApiRequest$outboundSchema.parse(
      clientRegistrationGetApiRequest,
    ),
  );
}

/** @internal */
export const ClientRegistrationGetApiResponse$inboundSchema: z.ZodType<
  ClientRegistrationGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientRegistrationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientRegistrationGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientRegistrationGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientRegistrationGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientRegistrationGetApiResponse' from JSON`,
  );
}
