/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ClientExtensionRequestablesScopesDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
};

export type ClientExtensionRequestablesScopesDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type ClientExtensionRequestablesScopesDeleteApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
};

/** @internal */
export const ClientExtensionRequestablesScopesDeleteApiRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesDeleteApiRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesDeleteApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
  });

export function clientExtensionRequestablesScopesDeleteApiRequestToJSON(
  clientExtensionRequestablesScopesDeleteApiRequest:
    ClientExtensionRequestablesScopesDeleteApiRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesDeleteApiRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesDeleteApiRequest,
    ),
  );
}

/** @internal */
export const ClientExtensionRequestablesScopesDeleteApiResponse$inboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesDeleteApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  });

export function clientExtensionRequestablesScopesDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientExtensionRequestablesScopesDeleteApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientExtensionRequestablesScopesDeleteApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientExtensionRequestablesScopesDeleteApiResponse' from JSON`,
  );
}
