/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  clientAuthorizationUpdateRequest?:
    | models.ClientAuthorizationUpdateRequest
    | undefined;
};

export type ClientAuthorizationUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationUpdateResponse;
};

/** @internal */
export type ClientAuthorizationUpdateApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  client_authorization_update_request?:
    | models.ClientAuthorizationUpdateRequest$Outbound
    | undefined;
};

/** @internal */
export const ClientAuthorizationUpdateApiRequest$outboundSchema: z.ZodType<
  ClientAuthorizationUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  clientAuthorizationUpdateRequest: models
    .ClientAuthorizationUpdateRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    clientAuthorizationUpdateRequest: "client_authorization_update_request",
  });
});

export function clientAuthorizationUpdateApiRequestToJSON(
  clientAuthorizationUpdateApiRequest: ClientAuthorizationUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationUpdateApiRequest$outboundSchema.parse(
      clientAuthorizationUpdateApiRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationUpdateApiResponse$inboundSchema: z.ZodType<
  ClientAuthorizationUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationUpdateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientAuthorizationUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientAuthorizationUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientAuthorizationUpdateApiResponse' from JSON`,
  );
}
