/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientSecretUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The client ID or the client ID alias of a client.
   *
   * @remarks
   */
  clientIdentifier: string;
  clientSecretUpdateRequest: models.ClientSecretUpdateRequest;
};

export type ClientSecretUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientSecretUpdateResponse;
};

/** @internal */
export type ClientSecretUpdateApiRequest$Outbound = {
  serviceId: string;
  clientIdentifier: string;
  client_secret_update_request: models.ClientSecretUpdateRequest$Outbound;
};

/** @internal */
export const ClientSecretUpdateApiRequest$outboundSchema: z.ZodType<
  ClientSecretUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientSecretUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  clientIdentifier: z.string(),
  clientSecretUpdateRequest: models.ClientSecretUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    clientSecretUpdateRequest: "client_secret_update_request",
  });
});

export function clientSecretUpdateApiRequestToJSON(
  clientSecretUpdateApiRequest: ClientSecretUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientSecretUpdateApiRequest$outboundSchema.parse(
      clientSecretUpdateApiRequest,
    ),
  );
}

/** @internal */
export const ClientSecretUpdateApiResponse$inboundSchema: z.ZodType<
  ClientSecretUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientSecretUpdateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientSecretUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientSecretUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientSecretUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientSecretUpdateApiResponse' from JSON`,
  );
}
