/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGetListApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The developer of client applications. The default value is null. If this parameter is not set
   *
   * @remarks
   * to `null`, client application of the specified developer are returned. Otherwise, all client
   * applications that belong to the service are returned.
   */
  developer?: string | undefined;
  /**
   * Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
   */
  start?: number | undefined;
  /**
   * End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
   */
  end?: number | undefined;
};

export type ClientGetListApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientGetListResponse;
};

/** @internal */
export type ClientGetListApiRequest$Outbound = {
  serviceId: string;
  developer?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

/** @internal */
export const ClientGetListApiRequest$outboundSchema: z.ZodType<
  ClientGetListApiRequest$Outbound,
  z.ZodTypeDef,
  ClientGetListApiRequest
> = z.object({
  serviceId: z.string(),
  developer: z.string().optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
});

export function clientGetListApiRequestToJSON(
  clientGetListApiRequest: ClientGetListApiRequest,
): string {
  return JSON.stringify(
    ClientGetListApiRequest$outboundSchema.parse(clientGetListApiRequest),
  );
}

/** @internal */
export const ClientGetListApiResponse$inboundSchema: z.ZodType<
  ClientGetListApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientGetListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientGetListApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGetListApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientGetListApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGetListApiResponse' from JSON`,
  );
}
