/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientUpdateApiFormRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   */
  clientId: string;
  requestBody?: { [k: string]: any } | undefined;
};

export type ClientUpdateApiFormResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Client;
};

/** @internal */
export type ClientUpdateApiFormRequest$Outbound = {
  serviceId: string;
  clientId: string;
  RequestBody?: { [k: string]: any } | undefined;
};

/** @internal */
export const ClientUpdateApiFormRequest$outboundSchema: z.ZodType<
  ClientUpdateApiFormRequest$Outbound,
  z.ZodTypeDef,
  ClientUpdateApiFormRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  requestBody: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientUpdateApiFormRequestToJSON(
  clientUpdateApiFormRequest: ClientUpdateApiFormRequest,
): string {
  return JSON.stringify(
    ClientUpdateApiFormRequest$outboundSchema.parse(clientUpdateApiFormRequest),
  );
}

/** @internal */
export const ClientUpdateApiFormResponse$inboundSchema: z.ZodType<
  ClientUpdateApiFormResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Client$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientUpdateApiFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientUpdateApiFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientUpdateApiFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientUpdateApiFormResponse' from JSON`,
  );
}
