/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGrantedScopesGetBySubjectApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientGrantedScopesGetBySubjectApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientGrantedScopesGetBySubjectApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientGrantedScopesGetBySubjectApiRequest$outboundSchema:
  z.ZodType<
    ClientGrantedScopesGetBySubjectApiRequest$Outbound,
    z.ZodTypeDef,
    ClientGrantedScopesGetBySubjectApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    subject: z.string(),
  });

export function clientGrantedScopesGetBySubjectApiRequestToJSON(
  clientGrantedScopesGetBySubjectApiRequest:
    ClientGrantedScopesGetBySubjectApiRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesGetBySubjectApiRequest$outboundSchema.parse(
      clientGrantedScopesGetBySubjectApiRequest,
    ),
  );
}

/** @internal */
export const ClientGrantedScopesGetBySubjectApiResponse$inboundSchema:
  z.ZodType<ClientGrantedScopesGetBySubjectApiResponse, z.ZodTypeDef, unknown> =
    z.object({
      Headers: z.record(z.array(z.string())).default({}),
      Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
    }).transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    });

export function clientGrantedScopesGetBySubjectApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientGrantedScopesGetBySubjectApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientGrantedScopesGetBySubjectApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientGrantedScopesGetBySubjectApiResponse' from JSON`,
  );
}
