/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientExtensionRequestablesScopesUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  clientExtensionRequestableScopesUpdateRequest:
    models.ClientExtensionRequestableScopesUpdateRequest;
};

export type ClientExtensionRequestablesScopesUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientExtensionRequestableScopesUpdateResponse;
};

/** @internal */
export type ClientExtensionRequestablesScopesUpdateApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  client_extension_requestable_scopes_update_request:
    models.ClientExtensionRequestableScopesUpdateRequest$Outbound;
};

/** @internal */
export const ClientExtensionRequestablesScopesUpdateApiRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesUpdateApiRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesUpdateApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    clientExtensionRequestableScopesUpdateRequest:
      models.ClientExtensionRequestableScopesUpdateRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      clientExtensionRequestableScopesUpdateRequest:
        "client_extension_requestable_scopes_update_request",
    });
  });

export function clientExtensionRequestablesScopesUpdateApiRequestToJSON(
  clientExtensionRequestablesScopesUpdateApiRequest:
    ClientExtensionRequestablesScopesUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesUpdateApiRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesUpdateApiRequest,
    ),
  );
}

/** @internal */
export const ClientExtensionRequestablesScopesUpdateApiResponse$inboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesUpdateApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: models.ClientExtensionRequestableScopesUpdateResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function clientExtensionRequestablesScopesUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientExtensionRequestablesScopesUpdateApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientExtensionRequestablesScopesUpdateApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientExtensionRequestablesScopesUpdateApiResponse' from JSON`,
  );
}
