/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientGrantedScopesGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientGrantedScopesGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientGrantedScopesGetApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientGrantedScopesGetApiRequest$outboundSchema: z.ZodType<
  ClientGrantedScopesGetApiRequest$Outbound,
  z.ZodTypeDef,
  ClientGrantedScopesGetApiRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  subject: z.string(),
});

export function clientGrantedScopesGetApiRequestToJSON(
  clientGrantedScopesGetApiRequest: ClientGrantedScopesGetApiRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesGetApiRequest$outboundSchema.parse(
      clientGrantedScopesGetApiRequest,
    ),
  );
}

/** @internal */
export const ClientGrantedScopesGetApiResponse$inboundSchema: z.ZodType<
  ClientGrantedScopesGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientGrantedScopesGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGrantedScopesGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientGrantedScopesGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGrantedScopesGetApiResponse' from JSON`,
  );
}
