/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientAuthorizationDeleteBySubjectApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

export type ClientAuthorizationDeleteBySubjectApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientAuthorizationDeleteResponse;
};

/** @internal */
export type ClientAuthorizationDeleteBySubjectApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientAuthorizationDeleteBySubjectApiRequest$outboundSchema:
  z.ZodType<
    ClientAuthorizationDeleteBySubjectApiRequest$Outbound,
    z.ZodTypeDef,
    ClientAuthorizationDeleteBySubjectApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    subject: z.string(),
  });

export function clientAuthorizationDeleteBySubjectApiRequestToJSON(
  clientAuthorizationDeleteBySubjectApiRequest:
    ClientAuthorizationDeleteBySubjectApiRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteBySubjectApiRequest$outboundSchema.parse(
      clientAuthorizationDeleteBySubjectApiRequest,
    ),
  );
}

/** @internal */
export const ClientAuthorizationDeleteBySubjectApiResponse$inboundSchema:
  z.ZodType<
    ClientAuthorizationDeleteBySubjectApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: models.ClientAuthorizationDeleteResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function clientAuthorizationDeleteBySubjectApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientAuthorizationDeleteBySubjectApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationDeleteBySubjectApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientAuthorizationDeleteBySubjectApiResponse' from JSON`,
  );
}
