/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientExtensionRequestablesScopesGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
};

export type ClientExtensionRequestablesScopesGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ClientExtensionRequestableScopesGetResponse;
};

/** @internal */
export type ClientExtensionRequestablesScopesGetApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
};

/** @internal */
export const ClientExtensionRequestablesScopesGetApiRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesGetApiRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesGetApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
  });

export function clientExtensionRequestablesScopesGetApiRequestToJSON(
  clientExtensionRequestablesScopesGetApiRequest:
    ClientExtensionRequestablesScopesGetApiRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesGetApiRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesGetApiRequest,
    ),
  );
}

/** @internal */
export const ClientExtensionRequestablesScopesGetApiResponse$inboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesGetApiResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: models.ClientExtensionRequestableScopesGetResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function clientExtensionRequestablesScopesGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientExtensionRequestablesScopesGetApiResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientExtensionRequestablesScopesGetApiResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientExtensionRequestablesScopesGetApiResponse' from JSON`,
  );
}
