/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ClientCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  client?: models.ClientInput | undefined;
};

export type ClientCreateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Client;
};

/** @internal */
export type ClientCreateApiRequest$Outbound = {
  serviceId: string;
  client?: models.ClientInput$Outbound | undefined;
};

/** @internal */
export const ClientCreateApiRequest$outboundSchema: z.ZodType<
  ClientCreateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientCreateApiRequest
> = z.object({
  serviceId: z.string(),
  client: models.ClientInput$outboundSchema.optional(),
});

export function clientCreateApiRequestToJSON(
  clientCreateApiRequest: ClientCreateApiRequest,
): string {
  return JSON.stringify(
    ClientCreateApiRequest$outboundSchema.parse(clientCreateApiRequest),
  );
}

/** @internal */
export const ClientCreateApiResponse$inboundSchema: z.ZodType<
  ClientCreateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Client$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function clientCreateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientCreateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientCreateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientCreateApiResponse' from JSON`,
  );
}
