/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeviceAuthorizationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  deviceAuthorizationRequest: models.DeviceAuthorizationRequest;
};

export type DeviceAuthorizationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.DeviceAuthorizationResponse;
};

/** @internal */
export type DeviceAuthorizationApiRequest$Outbound = {
  serviceId: string;
  device_authorization_request: models.DeviceAuthorizationRequest$Outbound;
};

/** @internal */
export const DeviceAuthorizationApiRequest$outboundSchema: z.ZodType<
  DeviceAuthorizationApiRequest$Outbound,
  z.ZodTypeDef,
  DeviceAuthorizationApiRequest
> = z.object({
  serviceId: z.string(),
  deviceAuthorizationRequest: models.DeviceAuthorizationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deviceAuthorizationRequest: "device_authorization_request",
  });
});

export function deviceAuthorizationApiRequestToJSON(
  deviceAuthorizationApiRequest: DeviceAuthorizationApiRequest,
): string {
  return JSON.stringify(
    DeviceAuthorizationApiRequest$outboundSchema.parse(
      deviceAuthorizationApiRequest,
    ),
  );
}

/** @internal */
export const DeviceAuthorizationApiResponse$inboundSchema: z.ZodType<
  DeviceAuthorizationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.DeviceAuthorizationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deviceAuthorizationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceAuthorizationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceAuthorizationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceAuthorizationApiResponse' from JSON`,
  );
}
