/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeviceVerificationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  deviceVerificationRequest: models.DeviceVerificationRequest;
};

export type DeviceVerificationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.DeviceVerificationResponse;
};

/** @internal */
export type DeviceVerificationApiRequest$Outbound = {
  serviceId: string;
  device_verification_request: models.DeviceVerificationRequest$Outbound;
};

/** @internal */
export const DeviceVerificationApiRequest$outboundSchema: z.ZodType<
  DeviceVerificationApiRequest$Outbound,
  z.ZodTypeDef,
  DeviceVerificationApiRequest
> = z.object({
  serviceId: z.string(),
  deviceVerificationRequest: models.DeviceVerificationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deviceVerificationRequest: "device_verification_request",
  });
});

export function deviceVerificationApiRequestToJSON(
  deviceVerificationApiRequest: DeviceVerificationApiRequest,
): string {
  return JSON.stringify(
    DeviceVerificationApiRequest$outboundSchema.parse(
      deviceVerificationApiRequest,
    ),
  );
}

/** @internal */
export const DeviceVerificationApiResponse$inboundSchema: z.ZodType<
  DeviceVerificationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.DeviceVerificationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deviceVerificationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceVerificationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceVerificationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceVerificationApiResponse' from JSON`,
  );
}
