/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeviceCompleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  deviceCompleteRequest: models.DeviceCompleteRequest;
};

export type DeviceCompleteApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.DeviceCompleteResponse;
};

/** @internal */
export type DeviceCompleteApiRequest$Outbound = {
  serviceId: string;
  device_complete_request: models.DeviceCompleteRequest$Outbound;
};

/** @internal */
export const DeviceCompleteApiRequest$outboundSchema: z.ZodType<
  DeviceCompleteApiRequest$Outbound,
  z.ZodTypeDef,
  DeviceCompleteApiRequest
> = z.object({
  serviceId: z.string(),
  deviceCompleteRequest: models.DeviceCompleteRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deviceCompleteRequest: "device_complete_request",
  });
});

export function deviceCompleteApiRequestToJSON(
  deviceCompleteApiRequest: DeviceCompleteApiRequest,
): string {
  return JSON.stringify(
    DeviceCompleteApiRequest$outboundSchema.parse(deviceCompleteApiRequest),
  );
}

/** @internal */
export const DeviceCompleteApiResponse$inboundSchema: z.ZodType<
  DeviceCompleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.DeviceCompleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function deviceCompleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceCompleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceCompleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceCompleteApiResponse' from JSON`,
  );
}
