/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type FederationRegistrationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  federationRegistrationRequest: models.FederationRegistrationRequest;
};

export type FederationRegistrationApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.FederationRegistrationResponse;
};

/** @internal */
export type FederationRegistrationApiRequest$Outbound = {
  serviceId: string;
  federation_registration_request:
    models.FederationRegistrationRequest$Outbound;
};

/** @internal */
export const FederationRegistrationApiRequest$outboundSchema: z.ZodType<
  FederationRegistrationApiRequest$Outbound,
  z.ZodTypeDef,
  FederationRegistrationApiRequest
> = z.object({
  serviceId: z.string(),
  federationRegistrationRequest:
    models.FederationRegistrationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    federationRegistrationRequest: "federation_registration_request",
  });
});

export function federationRegistrationApiRequestToJSON(
  federationRegistrationApiRequest: FederationRegistrationApiRequest,
): string {
  return JSON.stringify(
    FederationRegistrationApiRequest$outboundSchema.parse(
      federationRegistrationApiRequest,
    ),
  );
}

/** @internal */
export const FederationRegistrationApiResponse$inboundSchema: z.ZodType<
  FederationRegistrationApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.FederationRegistrationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function federationRegistrationApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<FederationRegistrationApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FederationRegistrationApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FederationRegistrationApiResponse' from JSON`,
  );
}
