/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GrantMApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  gMRequest: models.GMRequest;
};

export type GrantMApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GMResponse;
};

/** @internal */
export type GrantMApiRequest$Outbound = {
  serviceId: string;
  g_m_request: models.GMRequest$Outbound;
};

/** @internal */
export const GrantMApiRequest$outboundSchema: z.ZodType<
  GrantMApiRequest$Outbound,
  z.ZodTypeDef,
  GrantMApiRequest
> = z.object({
  serviceId: z.string(),
  gMRequest: models.GMRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    gMRequest: "g_m_request",
  });
});

export function grantMApiRequestToJSON(
  grantMApiRequest: GrantMApiRequest,
): string {
  return JSON.stringify(
    GrantMApiRequest$outboundSchema.parse(grantMApiRequest),
  );
}

/** @internal */
export const GrantMApiResponse$inboundSchema: z.ZodType<
  GrantMApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.GMResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function grantMApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<GrantMApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GrantMApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GrantMApiResponse' from JSON`,
  );
}
