/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type HskCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  hskCreateRequest: models.HskCreateRequest;
};

export type HskCreateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.HskCreateResponse;
};

/** @internal */
export type HskCreateApiRequest$Outbound = {
  serviceId: string;
  hsk_create_request: models.HskCreateRequest$Outbound;
};

/** @internal */
export const HskCreateApiRequest$outboundSchema: z.ZodType<
  HskCreateApiRequest$Outbound,
  z.ZodTypeDef,
  HskCreateApiRequest
> = z.object({
  serviceId: z.string(),
  hskCreateRequest: models.HskCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    hskCreateRequest: "hsk_create_request",
  });
});

export function hskCreateApiRequestToJSON(
  hskCreateApiRequest: HskCreateApiRequest,
): string {
  return JSON.stringify(
    HskCreateApiRequest$outboundSchema.parse(hskCreateApiRequest),
  );
}

/** @internal */
export const HskCreateApiResponse$inboundSchema: z.ZodType<
  HskCreateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.HskCreateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function hskCreateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskCreateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskCreateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskCreateApiResponse' from JSON`,
  );
}
