/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type HskDeleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  handle: string;
};

export type HskDeleteApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.HskDeleteResponse;
};

/** @internal */
export type HskDeleteApiRequest$Outbound = {
  serviceId: string;
  handle: string;
};

/** @internal */
export const HskDeleteApiRequest$outboundSchema: z.ZodType<
  HskDeleteApiRequest$Outbound,
  z.ZodTypeDef,
  HskDeleteApiRequest
> = z.object({
  serviceId: z.string(),
  handle: z.string(),
});

export function hskDeleteApiRequestToJSON(
  hskDeleteApiRequest: HskDeleteApiRequest,
): string {
  return JSON.stringify(
    HskDeleteApiRequest$outboundSchema.parse(hskDeleteApiRequest),
  );
}

/** @internal */
export const HskDeleteApiResponse$inboundSchema: z.ZodType<
  HskDeleteApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.HskDeleteResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function hskDeleteApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskDeleteApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskDeleteApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskDeleteApiResponse' from JSON`,
  );
}
