/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type HskGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  handle: string;
};

export type HskGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.HskGetResponse;
};

/** @internal */
export type HskGetApiRequest$Outbound = {
  serviceId: string;
  handle: string;
};

/** @internal */
export const HskGetApiRequest$outboundSchema: z.ZodType<
  HskGetApiRequest$Outbound,
  z.ZodTypeDef,
  HskGetApiRequest
> = z.object({
  serviceId: z.string(),
  handle: z.string(),
});

export function hskGetApiRequestToJSON(
  hskGetApiRequest: HskGetApiRequest,
): string {
  return JSON.stringify(
    HskGetApiRequest$outboundSchema.parse(hskGetApiRequest),
  );
}

/** @internal */
export const HskGetApiResponse$inboundSchema: z.ZodType<
  HskGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.HskGetResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function hskGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskGetApiResponse' from JSON`,
  );
}
