/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IdtokenReissueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  idtokenReissueRequest?: models.IdtokenReissueRequest | undefined;
};

export type IdtokenReissueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.IdtokenReissueResponse;
};

/** @internal */
export type IdtokenReissueApiRequest$Outbound = {
  serviceId: string;
  idtoken_reissue_request?: models.IdtokenReissueRequest$Outbound | undefined;
};

/** @internal */
export const IdtokenReissueApiRequest$outboundSchema: z.ZodType<
  IdtokenReissueApiRequest$Outbound,
  z.ZodTypeDef,
  IdtokenReissueApiRequest
> = z.object({
  serviceId: z.string(),
  idtokenReissueRequest: models.IdtokenReissueRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    idtokenReissueRequest: "idtoken_reissue_request",
  });
});

export function idtokenReissueApiRequestToJSON(
  idtokenReissueApiRequest: IdtokenReissueApiRequest,
): string {
  return JSON.stringify(
    IdtokenReissueApiRequest$outboundSchema.parse(idtokenReissueApiRequest),
  );
}

/** @internal */
export const IdtokenReissueApiResponse$inboundSchema: z.ZodType<
  IdtokenReissueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.IdtokenReissueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function idtokenReissueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdtokenReissueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdtokenReissueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdtokenReissueApiResponse' from JSON`,
  );
}
