/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type NativeSsoApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  nativeSsoRequest: models.NativeSsoRequest;
};

export type NativeSsoApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.NativeSsoResponse;
};

/** @internal */
export type NativeSsoApiRequest$Outbound = {
  serviceId: string;
  native_sso_request: models.NativeSsoRequest$Outbound;
};

/** @internal */
export const NativeSsoApiRequest$outboundSchema: z.ZodType<
  NativeSsoApiRequest$Outbound,
  z.ZodTypeDef,
  NativeSsoApiRequest
> = z.object({
  serviceId: z.string(),
  nativeSsoRequest: models.NativeSsoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    nativeSsoRequest: "native_sso_request",
  });
});

export function nativeSsoApiRequestToJSON(
  nativeSsoApiRequest: NativeSsoApiRequest,
): string {
  return JSON.stringify(
    NativeSsoApiRequest$outboundSchema.parse(nativeSsoApiRequest),
  );
}

/** @internal */
export const NativeSsoApiResponse$inboundSchema: z.ZodType<
  NativeSsoApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.NativeSsoResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function nativeSsoApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<NativeSsoApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NativeSsoApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NativeSsoApiResponse' from JSON`,
  );
}
