/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type NativeSsoLogoutApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  nativeSsoLogoutRequest: models.NativeSsoLogoutRequest;
};

export type NativeSsoLogoutApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.NativeSsoLogoutResponse;
};

/** @internal */
export type NativeSsoLogoutApiRequest$Outbound = {
  serviceId: string;
  native_sso_logout_request: models.NativeSsoLogoutRequest$Outbound;
};

/** @internal */
export const NativeSsoLogoutApiRequest$outboundSchema: z.ZodType<
  NativeSsoLogoutApiRequest$Outbound,
  z.ZodTypeDef,
  NativeSsoLogoutApiRequest
> = z.object({
  serviceId: z.string(),
  nativeSsoLogoutRequest: models.NativeSsoLogoutRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    nativeSsoLogoutRequest: "native_sso_logout_request",
  });
});

export function nativeSsoLogoutApiRequestToJSON(
  nativeSsoLogoutApiRequest: NativeSsoLogoutApiRequest,
): string {
  return JSON.stringify(
    NativeSsoLogoutApiRequest$outboundSchema.parse(nativeSsoLogoutApiRequest),
  );
}

/** @internal */
export const NativeSsoLogoutApiResponse$inboundSchema: z.ZodType<
  NativeSsoLogoutApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.NativeSsoLogoutResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function nativeSsoLogoutApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<NativeSsoLogoutApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NativeSsoLogoutApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NativeSsoLogoutApiResponse' from JSON`,
  );
}
