/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PushedAuthReqApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  pushedAuthorizationRequest: models.PushedAuthorizationRequest;
};

export type PushedAuthReqApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.PushedAuthorizationResponse;
};

/** @internal */
export type PushedAuthReqApiRequest$Outbound = {
  serviceId: string;
  pushed_authorization_request: models.PushedAuthorizationRequest$Outbound;
};

/** @internal */
export const PushedAuthReqApiRequest$outboundSchema: z.ZodType<
  PushedAuthReqApiRequest$Outbound,
  z.ZodTypeDef,
  PushedAuthReqApiRequest
> = z.object({
  serviceId: z.string(),
  pushedAuthorizationRequest: models.PushedAuthorizationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    pushedAuthorizationRequest: "pushed_authorization_request",
  });
});

export function pushedAuthReqApiRequestToJSON(
  pushedAuthReqApiRequest: PushedAuthReqApiRequest,
): string {
  return JSON.stringify(
    PushedAuthReqApiRequest$outboundSchema.parse(pushedAuthReqApiRequest),
  );
}

/** @internal */
export const PushedAuthReqApiResponse$inboundSchema: z.ZodType<
  PushedAuthReqApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.PushedAuthorizationResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function pushedAuthReqApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<PushedAuthReqApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PushedAuthReqApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PushedAuthReqApiResponse' from JSON`,
  );
}
