/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServiceUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  service?: models.ServiceInput | undefined;
};

export type ServiceUpdateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Service;
};

/** @internal */
export type ServiceUpdateApiRequest$Outbound = {
  serviceId: string;
  service?: models.ServiceInput$Outbound | undefined;
};

/** @internal */
export const ServiceUpdateApiRequest$outboundSchema: z.ZodType<
  ServiceUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ServiceUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  service: models.ServiceInput$outboundSchema.optional(),
});

export function serviceUpdateApiRequestToJSON(
  serviceUpdateApiRequest: ServiceUpdateApiRequest,
): string {
  return JSON.stringify(
    ServiceUpdateApiRequest$outboundSchema.parse(serviceUpdateApiRequest),
  );
}

/** @internal */
export const ServiceUpdateApiResponse$inboundSchema: z.ZodType<
  ServiceUpdateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Service$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function serviceUpdateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServiceUpdateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServiceUpdateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServiceUpdateApiResponse' from JSON`,
  );
}
