/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * IDP Server
 */
export const ServiceCreateIdpApiServerIdp = "idp";

export const ServiceCreateIdpApiServerList = {
  [ServiceCreateIdpApiServerIdp]: "https://login.authlete.com",
};
