/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * IDP Server
 */
export const ServiceRemoveIdpApiServerIdp = "idp";

export const ServiceRemoveIdpApiServerList = {
  [ServiceRemoveIdpApiServerIdp]: "https://login.authlete.com",
};
