/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServiceJwksGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The boolean value that indicates whether the response should include the private keys associated with the service or not. If `true`, the private keys are included in the response. The default value is `false`.
   */
  includePrivateKeys?: boolean | undefined;
  /**
   * This boolean value indicates whether the JSON in the response should be formatted or not. If `true`, the JSON in the response is pretty-formatted. The default value is `false`.
   */
  pretty?: boolean | undefined;
};

export type ServiceJwksGetApiResponse = {
  headers: { [k: string]: Array<string> };
  result?: models.ServiceJwksGetResponse | undefined;
};

/** @internal */
export type ServiceJwksGetApiRequest$Outbound = {
  serviceId: string;
  includePrivateKeys?: boolean | undefined;
  pretty?: boolean | undefined;
};

/** @internal */
export const ServiceJwksGetApiRequest$outboundSchema: z.ZodType<
  ServiceJwksGetApiRequest$Outbound,
  z.ZodTypeDef,
  ServiceJwksGetApiRequest
> = z.object({
  serviceId: z.string(),
  includePrivateKeys: z.boolean().optional(),
  pretty: z.boolean().optional(),
});

export function serviceJwksGetApiRequestToJSON(
  serviceJwksGetApiRequest: ServiceJwksGetApiRequest,
): string {
  return JSON.stringify(
    ServiceJwksGetApiRequest$outboundSchema.parse(serviceJwksGetApiRequest),
  );
}

/** @internal */
export const ServiceJwksGetApiResponse$inboundSchema: z.ZodType<
  ServiceJwksGetApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.ServiceJwksGetResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function serviceJwksGetApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServiceJwksGetApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServiceJwksGetApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServiceJwksGetApiResponse' from JSON`,
  );
}
