/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateAuthorizationTicketRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationTicketUpdateRequest: models.AuthorizationTicketUpdateRequest;
};

export type UpdateAuthorizationTicketResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuthorizationTicketUpdateResponse;
};

/** @internal */
export type UpdateAuthorizationTicketRequest$Outbound = {
  serviceId: string;
  authorization_ticket_update_request:
    models.AuthorizationTicketUpdateRequest$Outbound;
};

/** @internal */
export const UpdateAuthorizationTicketRequest$outboundSchema: z.ZodType<
  UpdateAuthorizationTicketRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuthorizationTicketRequest
> = z.object({
  serviceId: z.string(),
  authorizationTicketUpdateRequest:
    models.AuthorizationTicketUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationTicketUpdateRequest: "authorization_ticket_update_request",
  });
});

export function updateAuthorizationTicketRequestToJSON(
  updateAuthorizationTicketRequest: UpdateAuthorizationTicketRequest,
): string {
  return JSON.stringify(
    UpdateAuthorizationTicketRequest$outboundSchema.parse(
      updateAuthorizationTicketRequest,
    ),
  );
}

/** @internal */
export const UpdateAuthorizationTicketResponse$inboundSchema: z.ZodType<
  UpdateAuthorizationTicketResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AuthorizationTicketUpdateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function updateAuthorizationTicketResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAuthorizationTicketResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAuthorizationTicketResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAuthorizationTicketResponse' from JSON`,
  );
}
