/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciBatchParseApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciBatchParseRequest: models.VciBatchParseRequest;
};

export type VciBatchParseApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciBatchParseResponse;
};

/** @internal */
export type VciBatchParseApiRequest$Outbound = {
  serviceId: string;
  vci_batch_parse_request: models.VciBatchParseRequest$Outbound;
};

/** @internal */
export const VciBatchParseApiRequest$outboundSchema: z.ZodType<
  VciBatchParseApiRequest$Outbound,
  z.ZodTypeDef,
  VciBatchParseApiRequest
> = z.object({
  serviceId: z.string(),
  vciBatchParseRequest: models.VciBatchParseRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciBatchParseRequest: "vci_batch_parse_request",
  });
});

export function vciBatchParseApiRequestToJSON(
  vciBatchParseApiRequest: VciBatchParseApiRequest,
): string {
  return JSON.stringify(
    VciBatchParseApiRequest$outboundSchema.parse(vciBatchParseApiRequest),
  );
}

/** @internal */
export const VciBatchParseApiResponse$inboundSchema: z.ZodType<
  VciBatchParseApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciBatchParseResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciBatchParseApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciBatchParseApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciBatchParseApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciBatchParseApiResponse' from JSON`,
  );
}
