/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciDeferredIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciDeferredIssueRequest: models.VciDeferredIssueRequest;
};

export type VciDeferredIssueApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciDeferredIssueResponse;
};

/** @internal */
export type VciDeferredIssueApiRequest$Outbound = {
  serviceId: string;
  vci_deferred_issue_request: models.VciDeferredIssueRequest$Outbound;
};

/** @internal */
export const VciDeferredIssueApiRequest$outboundSchema: z.ZodType<
  VciDeferredIssueApiRequest$Outbound,
  z.ZodTypeDef,
  VciDeferredIssueApiRequest
> = z.object({
  serviceId: z.string(),
  vciDeferredIssueRequest: models.VciDeferredIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciDeferredIssueRequest: "vci_deferred_issue_request",
  });
});

export function vciDeferredIssueApiRequestToJSON(
  vciDeferredIssueApiRequest: VciDeferredIssueApiRequest,
): string {
  return JSON.stringify(
    VciDeferredIssueApiRequest$outboundSchema.parse(vciDeferredIssueApiRequest),
  );
}

/** @internal */
export const VciDeferredIssueApiResponse$inboundSchema: z.ZodType<
  VciDeferredIssueApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciDeferredIssueResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciDeferredIssueApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciDeferredIssueApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciDeferredIssueApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciDeferredIssueApiResponse' from JSON`,
  );
}
