/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciJwtissuerApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciJwtissuerRequest: models.VciJwtissuerRequest;
};

export type VciJwtissuerApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciJwtissuerResponse;
};

/** @internal */
export type VciJwtissuerApiRequest$Outbound = {
  serviceId: string;
  vci_jwtissuer_request: models.VciJwtissuerRequest$Outbound;
};

/** @internal */
export const VciJwtissuerApiRequest$outboundSchema: z.ZodType<
  VciJwtissuerApiRequest$Outbound,
  z.ZodTypeDef,
  VciJwtissuerApiRequest
> = z.object({
  serviceId: z.string(),
  vciJwtissuerRequest: models.VciJwtissuerRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciJwtissuerRequest: "vci_jwtissuer_request",
  });
});

export function vciJwtissuerApiRequestToJSON(
  vciJwtissuerApiRequest: VciJwtissuerApiRequest,
): string {
  return JSON.stringify(
    VciJwtissuerApiRequest$outboundSchema.parse(vciJwtissuerApiRequest),
  );
}

/** @internal */
export const VciJwtissuerApiResponse$inboundSchema: z.ZodType<
  VciJwtissuerApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciJwtissuerResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciJwtissuerApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciJwtissuerApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciJwtissuerApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciJwtissuerApiResponse' from JSON`,
  );
}
