/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciMetadataApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciMetadataRequest: models.VciMetadataRequest;
};

export type VciMetadataApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciMetadataResponse;
};

/** @internal */
export type VciMetadataApiRequest$Outbound = {
  serviceId: string;
  vci_metadata_request: models.VciMetadataRequest$Outbound;
};

/** @internal */
export const VciMetadataApiRequest$outboundSchema: z.ZodType<
  VciMetadataApiRequest$Outbound,
  z.ZodTypeDef,
  VciMetadataApiRequest
> = z.object({
  serviceId: z.string(),
  vciMetadataRequest: models.VciMetadataRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciMetadataRequest: "vci_metadata_request",
  });
});

export function vciMetadataApiRequestToJSON(
  vciMetadataApiRequest: VciMetadataApiRequest,
): string {
  return JSON.stringify(
    VciMetadataApiRequest$outboundSchema.parse(vciMetadataApiRequest),
  );
}

/** @internal */
export const VciMetadataApiResponse$inboundSchema: z.ZodType<
  VciMetadataApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciMetadataResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciMetadataApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciMetadataApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciMetadataApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciMetadataApiResponse' from JSON`,
  );
}
