/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciOfferCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciOfferCreateRequest: models.VciOfferCreateRequest;
};

export type VciOfferCreateApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciOfferCreateResponse;
};

/** @internal */
export type VciOfferCreateApiRequest$Outbound = {
  serviceId: string;
  vci_offer_create_request: models.VciOfferCreateRequest$Outbound;
};

/** @internal */
export const VciOfferCreateApiRequest$outboundSchema: z.ZodType<
  VciOfferCreateApiRequest$Outbound,
  z.ZodTypeDef,
  VciOfferCreateApiRequest
> = z.object({
  serviceId: z.string(),
  vciOfferCreateRequest: models.VciOfferCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciOfferCreateRequest: "vci_offer_create_request",
  });
});

export function vciOfferCreateApiRequestToJSON(
  vciOfferCreateApiRequest: VciOfferCreateApiRequest,
): string {
  return JSON.stringify(
    VciOfferCreateApiRequest$outboundSchema.parse(vciOfferCreateApiRequest),
  );
}

/** @internal */
export const VciOfferCreateApiResponse$inboundSchema: z.ZodType<
  VciOfferCreateApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciOfferCreateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciOfferCreateApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciOfferCreateApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciOfferCreateApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciOfferCreateApiResponse' from JSON`,
  );
}
