/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciOfferInfoApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciOfferInfoRequest: models.VciOfferInfoRequest;
};

export type VciOfferInfoApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciOfferInfoResponse;
};

/** @internal */
export type VciOfferInfoApiRequest$Outbound = {
  serviceId: string;
  vci_offer_info_request: models.VciOfferInfoRequest$Outbound;
};

/** @internal */
export const VciOfferInfoApiRequest$outboundSchema: z.ZodType<
  VciOfferInfoApiRequest$Outbound,
  z.ZodTypeDef,
  VciOfferInfoApiRequest
> = z.object({
  serviceId: z.string(),
  vciOfferInfoRequest: models.VciOfferInfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciOfferInfoRequest: "vci_offer_info_request",
  });
});

export function vciOfferInfoApiRequestToJSON(
  vciOfferInfoApiRequest: VciOfferInfoApiRequest,
): string {
  return JSON.stringify(
    VciOfferInfoApiRequest$outboundSchema.parse(vciOfferInfoApiRequest),
  );
}

/** @internal */
export const VciOfferInfoApiResponse$inboundSchema: z.ZodType<
  VciOfferInfoApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciOfferInfoResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciOfferInfoApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciOfferInfoApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciOfferInfoApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciOfferInfoApiResponse' from JSON`,
  );
}
