/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciSingleParseApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciSingleParseRequest: models.VciSingleParseRequest;
};

export type VciSingleParseApiResponse = {
  headers: { [k: string]: Array<string> };
  result: models.VciSingleParseResponse;
};

/** @internal */
export type VciSingleParseApiRequest$Outbound = {
  serviceId: string;
  vci_single_parse_request: models.VciSingleParseRequest$Outbound;
};

/** @internal */
export const VciSingleParseApiRequest$outboundSchema: z.ZodType<
  VciSingleParseApiRequest$Outbound,
  z.ZodTypeDef,
  VciSingleParseApiRequest
> = z.object({
  serviceId: z.string(),
  vciSingleParseRequest: models.VciSingleParseRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciSingleParseRequest: "vci_single_parse_request",
  });
});

export function vciSingleParseApiRequestToJSON(
  vciSingleParseApiRequest: VciSingleParseApiRequest,
): string {
  return JSON.stringify(
    VciSingleParseApiRequest$outboundSchema.parse(vciSingleParseApiRequest),
  );
}

/** @internal */
export const VciSingleParseApiResponse$inboundSchema: z.ZodType<
  VciSingleParseApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.VciSingleParseResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vciSingleParseApiResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciSingleParseApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciSingleParseApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciSingleParseApiResponse' from JSON`,
  );
}
