/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Whether the action completed successfully or failed.
 */
export const Status = {
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Whether the action completed successfully or failed.
 */
export type Status = ClosedEnum<typeof Status>;

export type AuditLogEntry = {
  /**
   * The audit event type (e.g. service.create, security.login).
   */
  event?: string | undefined;
  /**
   * Whether the action completed successfully or failed.
   */
  status?: Status | undefined;
  /**
   * When the event occurred (ISO 8601). May be null for entries without a recorded
   *
   * @remarks
   * timestamp; such entries are only returned on the first page of results.
   */
  timestamp?: Date | null | undefined;
  /**
   * The cluster or region where the event occurred.
   */
  cluster?: string | undefined;
  /**
   * The API path that triggered the event.
   */
  path?: string | undefined;
  /**
   * The IP address of the client that performed the action.
   */
  remoteAddr?: string | undefined;
  /**
   * The user agent of the client.
   */
  userAgent?: string | undefined;
  /**
   * The user or token that performed the action.
   */
  user?: string | undefined;
  /**
   * Additional event-specific metadata.
   */
  details?: { [k: string]: any } | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const AuditLogEntry$inboundSchema: z.ZodType<
  AuditLogEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  event: z.string().optional(),
  status: Status$inboundSchema.optional(),
  timestamp: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  cluster: z.string().optional(),
  path: z.string().optional(),
  remoteAddr: z.string().optional(),
  userAgent: z.string().optional(),
  user: z.string().optional(),
  details: z.record(z.any()).optional(),
});

export function auditLogEntryFromJSON(
  jsonString: string,
): SafeParseResult<AuditLogEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditLogEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditLogEntry' from JSON`,
  );
}
