/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { AuditLogEntry, AuditLogEntry$inboundSchema } from "./auditlogentry.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AuditEntriesGetResponse = {
  /**
   * The audit log entries on this page, in reverse chronological order. Entries sharing the
   *
   * @remarks
   * same timestamp are never split across pages, so a page may contain more than `limit` entries.
   */
  entries?: Array<AuditLogEntry> | undefined;
  /**
   * An opaque cursor pointing at the next page. Pass this value as the `cursor` parameter of the
   *
   * @remarks
   * next request to fetch the following page. Absent or `null` on the last page.
   */
  nextCursor?: string | null | undefined;
  /**
   * The effective page size limit applied to this response. May differ from the requested `limit`
   *
   * @remarks
   * if the requested value was outside the allowed range.
   */
  limit?: number | undefined;
};

/** @internal */
export const AuditEntriesGetResponse$inboundSchema: z.ZodType<
  AuditEntriesGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  entries: z.array(AuditLogEntry$inboundSchema).optional(),
  nextCursor: z.nullable(z.string()).optional(),
  limit: z.number().int().optional(),
});

export function auditEntriesGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuditEntriesGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEntriesGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEntriesGetResponse' from JSON`,
  );
}
