/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AuthorizationTicketInfo,
  AuthorizationTicketInfo$Outbound,
  AuthorizationTicketInfo$outboundSchema,
} from "./authorizationticketinfo.js";

export type AuthorizationTicketUpdateRequest = {
  /**
   * The ticket.
   */
  ticket: string;
  info: AuthorizationTicketInfo;
};

/** @internal */
export type AuthorizationTicketUpdateRequest$Outbound = {
  ticket: string;
  info: AuthorizationTicketInfo$Outbound;
};

/** @internal */
export const AuthorizationTicketUpdateRequest$outboundSchema: z.ZodType<
  AuthorizationTicketUpdateRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationTicketUpdateRequest
> = z.object({
  ticket: z.string(),
  info: AuthorizationTicketInfo$outboundSchema,
});

export function authorizationTicketUpdateRequestToJSON(
  authorizationTicketUpdateRequest: AuthorizationTicketUpdateRequest,
): string {
  return JSON.stringify(
    AuthorizationTicketUpdateRequest$outboundSchema.parse(
      authorizationTicketUpdateRequest,
    ),
  );
}
