/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackchannelLogoutTokenRequest = {
  /**
   * The identifier of the client application. Either a client ID or a client
   *
   * @remarks
   * alias.
   */
  clientIdentifier: string;
  /**
   * The subject (end-user) identifier. The logout token will be issued for
   *
   * @remarks
   * this subject. At least one of `subject` or `sessionId` must be provided.
   */
  subject?: string | undefined;
  /**
   * The session ID (`sid`) identifying the user session to log out. At least
   *
   * @remarks
   * one of `subject` or `sessionId` must be provided.
   */
  sessionId?: string | undefined;
};

/** @internal */
export type BackchannelLogoutTokenRequest$Outbound = {
  clientIdentifier: string;
  subject?: string | undefined;
  sessionId?: string | undefined;
};

/** @internal */
export const BackchannelLogoutTokenRequest$outboundSchema: z.ZodType<
  BackchannelLogoutTokenRequest$Outbound,
  z.ZodTypeDef,
  BackchannelLogoutTokenRequest
> = z.object({
  clientIdentifier: z.string(),
  subject: z.string().optional(),
  sessionId: z.string().optional(),
});

export function backchannelLogoutTokenRequestToJSON(
  backchannelLogoutTokenRequest: BackchannelLogoutTokenRequest,
): string {
  return JSON.stringify(
    BackchannelLogoutTokenRequest$outboundSchema.parse(
      backchannelLogoutTokenRequest,
    ),
  );
}
