/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The next action that the API caller should take.
 *
 * @remarks
 */
export const BackchannelLogoutTokenResponseAction = {
  Ok: "OK",
  ServerError: "SERVER_ERROR",
  CallerError: "CALLER_ERROR",
} as const;
/**
 * The next action that the API caller should take.
 *
 * @remarks
 */
export type BackchannelLogoutTokenResponseAction = ClosedEnum<
  typeof BackchannelLogoutTokenResponseAction
>;

export type BackchannelLogoutTokenResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the API caller should take.
   *
   * @remarks
   */
  action?: BackchannelLogoutTokenResponseAction | undefined;
  /**
   * The logout token issued for the client. The caller should deliver this
   *
   * @remarks
   * token to the client's `backchannelLogoutUri`.
   */
  logoutToken?: string | undefined;
  /**
   * The backchannel logout URI of the client. The caller should POST the
   *
   * @remarks
   * `logoutToken` to this URI.
   */
  backchannelLogoutUri?: string | undefined;
};

/** @internal */
export const BackchannelLogoutTokenResponseAction$inboundSchema:
  z.ZodNativeEnum<typeof BackchannelLogoutTokenResponseAction> = z.nativeEnum(
    BackchannelLogoutTokenResponseAction,
  );

/** @internal */
export const BackchannelLogoutTokenResponse$inboundSchema: z.ZodType<
  BackchannelLogoutTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: BackchannelLogoutTokenResponseAction$inboundSchema.optional(),
  logoutToken: z.string().optional(),
  backchannelLogoutUri: z.string().optional(),
});

export function backchannelLogoutTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<BackchannelLogoutTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BackchannelLogoutTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackchannelLogoutTokenResponse' from JSON`,
  );
}
