/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CredentialIssuerMetadata = {
  /**
   * The identifiers of the authorization servers that the credential issuer relies on for authorization.
   *
   * @remarks
   * This property corresponds to the authorization_servers metadata. When the credential issuer works
   * as an authorization server for itself, this property should be omitted.
   */
  authorizationServers?: Array<string> | undefined;
  /**
   * The identifier of a credential request.
   */
  credentialIssuer?: string | undefined;
  /**
   * The URL of the credential endpoint of the credential issuer.
   */
  credentialEndpoint?: string | undefined;
  /**
   * The URL of the batch credential endpoint of the credential issuer.
   */
  batchCredentialEndpoint?: string | undefined;
  /**
   * The URL of the deferred credential endpoint of the credential issuer.
   */
  deferredCredentialEndpoint?: string | undefined;
  /**
   * A JSON object describing supported credential configurations.
   *
   * @remarks
   * This property corresponds to the credential_configurations_supported metadata.
   * Note: Due to a breaking change in December 2023, this was changed from a JSON array to a JSON object.
   */
  credentialsSupported?: string | undefined;
  /**
   * The supported JWE `alg` algorithms for credential response encryption. This property corresponds
   *
   * @remarks
   * to the `credential_response_encryption.alg_values_supported` metadata.
   */
  credentialResponseEncryptionAlgValuesSupported?: Array<string> | undefined;
  /**
   * The supported JWE `enc` algorithms for credential response encryption. This property corresponds
   *
   * @remarks
   * to the `credential_response_encryption.enc_values_supported` metadata.
   */
  credentialResponseEncryptionEncValuesSupported?: Array<string> | undefined;
  /**
   * The boolean flag indicating whether credential response encryption is required. This property
   *
   * @remarks
   * corresponds to the `credential_response_encryption.encryption_required metadata`. If this flag
   * is `true`, every credential request to the credential issuer must include the `credential_response_encryption`
   * property.
   */
  requireCredentialResponseEncryption?: boolean | undefined;
  /**
   * The boolean flag indicating whether credential request encryption is required. This property
   *
   * @remarks
   * corresponds to the `credential_request_encryption.encryption_required` metadata. If this flag
   * is `true`, every credential request to the credential issuer must be encrypted.
   */
  requireCredentialRequestEncryption?: boolean | undefined;
  /**
   * The supported JWE `zip` (compression) algorithms for credential response encryption. This
   *
   * @remarks
   * property corresponds to the `credential_response_encryption.zip_values_supported` metadata.
   */
  credentialResponseEncryptionZipValuesSupported?: Array<string> | undefined;
  /**
   * The maximum array size for the `proofs` parameter in a credential request. This property
   *
   * @remarks
   * corresponds to the `batch_credential_issuance.batch_size` metadata. If the value of this
   * property is 2 or greater, the `batch_credential_issuance` parameter will appear in the
   * response from the credential issuer metadata endpoint.
   */
  batchSize?: number | undefined;
};

/** @internal */
export const CredentialIssuerMetadata$inboundSchema: z.ZodType<
  CredentialIssuerMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  authorizationServers: z.array(z.string()).optional(),
  credentialIssuer: z.string().optional(),
  credentialEndpoint: z.string().optional(),
  batchCredentialEndpoint: z.string().optional(),
  deferredCredentialEndpoint: z.string().optional(),
  credentialsSupported: z.string().optional(),
  credentialResponseEncryptionAlgValuesSupported: z.array(z.string())
    .optional(),
  credentialResponseEncryptionEncValuesSupported: z.array(z.string())
    .optional(),
  requireCredentialResponseEncryption: z.boolean().optional(),
  requireCredentialRequestEncryption: z.boolean().optional(),
  credentialResponseEncryptionZipValuesSupported: z.array(z.string())
    .optional(),
  batchSize: z.number().int().optional(),
});
/** @internal */
export type CredentialIssuerMetadata$Outbound = {
  authorizationServers?: Array<string> | undefined;
  credentialIssuer?: string | undefined;
  credentialEndpoint?: string | undefined;
  batchCredentialEndpoint?: string | undefined;
  deferredCredentialEndpoint?: string | undefined;
  credentialsSupported?: string | undefined;
  credentialResponseEncryptionAlgValuesSupported?: Array<string> | undefined;
  credentialResponseEncryptionEncValuesSupported?: Array<string> | undefined;
  requireCredentialResponseEncryption?: boolean | undefined;
  requireCredentialRequestEncryption?: boolean | undefined;
  credentialResponseEncryptionZipValuesSupported?: Array<string> | undefined;
  batchSize?: number | undefined;
};

/** @internal */
export const CredentialIssuerMetadata$outboundSchema: z.ZodType<
  CredentialIssuerMetadata$Outbound,
  z.ZodTypeDef,
  CredentialIssuerMetadata
> = z.object({
  authorizationServers: z.array(z.string()).optional(),
  credentialIssuer: z.string().optional(),
  credentialEndpoint: z.string().optional(),
  batchCredentialEndpoint: z.string().optional(),
  deferredCredentialEndpoint: z.string().optional(),
  credentialsSupported: z.string().optional(),
  credentialResponseEncryptionAlgValuesSupported: z.array(z.string())
    .optional(),
  credentialResponseEncryptionEncValuesSupported: z.array(z.string())
    .optional(),
  requireCredentialResponseEncryption: z.boolean().optional(),
  requireCredentialRequestEncryption: z.boolean().optional(),
  credentialResponseEncryptionZipValuesSupported: z.array(z.string())
    .optional(),
  batchSize: z.number().int().optional(),
});

export function credentialIssuerMetadataToJSON(
  credentialIssuerMetadata: CredentialIssuerMetadata,
): string {
  return JSON.stringify(
    CredentialIssuerMetadata$outboundSchema.parse(credentialIssuerMetadata),
  );
}
export function credentialIssuerMetadataFromJSON(
  jsonString: string,
): SafeParseResult<CredentialIssuerMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CredentialIssuerMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CredentialIssuerMetadata' from JSON`,
  );
}
