/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The entity type, as defined in OpenID Federation 1.0.
 *
 * @remarks
 */
export const EntityType = {
  OpenidRelyingParty: "OPENID_RELYING_PARTY",
  OpenidProvider: "OPENID_PROVIDER",
  OauthAuthorizationServer: "OAUTH_AUTHORIZATION_SERVER",
  OauthClient: "OAUTH_CLIENT",
  OauthResource: "OAUTH_RESOURCE",
  FederationEntity: "FEDERATION_ENTITY",
  OpenidCredentialIssuer: "OPENID_CREDENTIAL_ISSUER",
} as const;
/**
 * The entity type, as defined in OpenID Federation 1.0.
 *
 * @remarks
 */
export type EntityType = ClosedEnum<typeof EntityType>;

/** @internal */
export const EntityType$outboundSchema: z.ZodNativeEnum<typeof EntityType> = z
  .nativeEnum(EntityType);
