/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ServiceRemoveIdpRequest = {
  /**
   * The numeric ID of the API server the service belongs to. Official SDKs inject
   *
   * @remarks
   * this automatically for known Authlete clusters, so it can be omitted there;
   * all other callers must provide it.
   */
  apiServerId?: number | undefined;
  /**
   * The numeric ID of the organization the service belongs to.
   */
  organizationId: number;
  /**
   * The numeric ID of the service to delete.
   */
  serviceId: number;
};

/** @internal */
export type ServiceRemoveIdpRequest$Outbound = {
  apiServerId?: number | undefined;
  organizationId: number;
  serviceId: number;
};

/** @internal */
export const ServiceRemoveIdpRequest$outboundSchema: z.ZodType<
  ServiceRemoveIdpRequest$Outbound,
  z.ZodTypeDef,
  ServiceRemoveIdpRequest
> = z.object({
  apiServerId: z.number().int().optional(),
  organizationId: z.number().int(),
  serviceId: z.number().int(),
});

export function serviceRemoveIdpRequestToJSON(
  serviceRemoveIdpRequest: ServiceRemoveIdpRequest,
): string {
  return JSON.stringify(
    ServiceRemoveIdpRequest$outboundSchema.parse(serviceRemoveIdpRequest),
  );
}
