/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ServiceInput,
  ServiceInput$Outbound,
  ServiceInput$outboundSchema,
} from "./service.js";

export type ServiceCreateIdpRequest = {
  /**
   * The numeric ID of the API server to create the service on. Official SDKs inject
   *
   * @remarks
   * this automatically for known Authlete clusters, so it can be omitted there;
   * all other callers must provide it.
   */
  apiServerId?: number | undefined;
  /**
   * The numeric ID of the organization the service belongs to.
   */
  organizationId: number;
  service?: ServiceInput | undefined;
};

/** @internal */
export type ServiceCreateIdpRequest$Outbound = {
  apiServerId?: number | undefined;
  organizationId: number;
  service?: ServiceInput$Outbound | undefined;
};

/** @internal */
export const ServiceCreateIdpRequest$outboundSchema: z.ZodType<
  ServiceCreateIdpRequest$Outbound,
  z.ZodTypeDef,
  ServiceCreateIdpRequest
> = z.object({
  apiServerId: z.number().int().optional(),
  organizationId: z.number().int(),
  service: ServiceInput$outboundSchema.optional(),
});

export function serviceCreateIdpRequestToJSON(
  serviceCreateIdpRequest: ServiceCreateIdpRequest,
): string {
  return JSON.stringify(
    ServiceCreateIdpRequest$outboundSchema.parse(serviceCreateIdpRequest),
  );
}
