/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TokenRevokeResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The number of tokens revoked.
   *
   * @remarks
   *
   * If the target has more than 20 tokens, the response `count` will be 20 and the remainder is left untouched. To fully wipe them, call the endpoint repeatedly until `count` returns 0.
   */
  count?: number | undefined;
};

/** @internal */
export const TokenRevokeResponse$inboundSchema: z.ZodType<
  TokenRevokeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  count: z.number().int().optional(),
});

export function tokenRevokeResponseFromJSON(
  jsonString: string,
): SafeParseResult<TokenRevokeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenRevokeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenRevokeResponse' from JSON`,
  );
}
