/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TokenRevokeRequest = {
  /**
   * The identifier of an access token to revoke
   *
   * @remarks
   *
   * The hash of an access token is recognized as an identifier as well as the access token itself.
   */
  accessTokenIdentifier?: string | undefined;
  /**
   * The identifier of a refresh token to revoke.
   *
   * @remarks
   *
   * The hash of a refresh token is recognized as an identifier as well as the refresh token itself.
   */
  refreshTokenIdentifier?: string | undefined;
  /**
   * The client ID of the access token to be revoked.
   *
   * @remarks
   *
   * Both the numeric client ID and the alias are recognized as an identifier
   * of a client.
   *
   * Bulk revocation with `clientIdentifier` only or `clientIdentifier` + `subject` deletes at most **20 tokens per request** (the default of `token.revoke.count.max` in `ServerConfiguration.java`). If the target has more than 20 tokens, the response `count` will be 20 and the remainder is left untouched. To fully wipe them, call the endpoint repeatedly until `count` returns 0.
   */
  clientIdentifier?: string | undefined;
  /**
   * The subject of a resource owner.
   *
   * @remarks
   *
   * Bulk revocation with `clientIdentifier` + `subject` or `subject` only deletes at most **20 tokens per request** (the default of `token.revoke.count.max` in `ServerConfiguration.java`). If the target has more than 20 tokens, the response `count` will be 20 and the remainder is left untouched. To fully wipe them, call the endpoint repeatedly until `count` returns 0.
   */
  subject?: string | undefined;
};

/** @internal */
export type TokenRevokeRequest$Outbound = {
  accessTokenIdentifier?: string | undefined;
  refreshTokenIdentifier?: string | undefined;
  clientIdentifier?: string | undefined;
  subject?: string | undefined;
};

/** @internal */
export const TokenRevokeRequest$outboundSchema: z.ZodType<
  TokenRevokeRequest$Outbound,
  z.ZodTypeDef,
  TokenRevokeRequest
> = z.object({
  accessTokenIdentifier: z.string().optional(),
  refreshTokenIdentifier: z.string().optional(),
  clientIdentifier: z.string().optional(),
  subject: z.string().optional(),
});

export function tokenRevokeRequestToJSON(
  tokenRevokeRequest: TokenRevokeRequest,
): string {
  return JSON.stringify(
    TokenRevokeRequest$outboundSchema.parse(tokenRevokeRequest),
  );
}
