/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { Pair, Pair$Outbound, Pair$outboundSchema } from "./pair.js";

export type UserinfoIssueRequest = {
  /**
   * The access token that has been passed to the userinfo endpoint by the client application. In other words,
   *
   * @remarks
   * the access token which was contained in the userinfo request.
   */
  token: string;
  /**
   * Claims in JSON format. As for the format, see [OpenID Connect Core 1.0, 5.1. Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).
   *
   * @remarks
   */
  claims?: string | undefined;
  /**
   * The value of the `sub` claim. If the value of this request parameter is not empty, it is used as the value of
   *
   * @remarks
   * the `sub` claim. Otherwise, the value of the subject associated with the access token is used.
   */
  sub?: string | undefined;
  /**
   * Claim key-value pairs that are used to compute transformed claims.
   *
   * @remarks
   */
  claimsForTx?: string | undefined;
  /**
   * The Signature header value from the request.
   *
   * @remarks
   */
  requestSignature?: string | undefined;
  /**
   * HTTP headers to be included in processing the signature. If this is a signed request, this must include the
   *
   * @remarks
   * Signature and Signature-Input headers, as well as any additional headers covered by the signature.
   */
  headers?: Array<Pair> | undefined;
  /**
   * Values of verified claims requested indirectly by "transformed claims".
   *
   * @remarks
   */
  verifiedClaimsForTx?: Array<string> | undefined;
};

/** @internal */
export type UserinfoIssueRequest$Outbound = {
  token: string;
  claims?: string | undefined;
  sub?: string | undefined;
  claimsForTx?: string | undefined;
  requestSignature?: string | undefined;
  headers?: Array<Pair$Outbound> | undefined;
  verifiedClaimsForTx?: Array<string> | undefined;
};

/** @internal */
export const UserinfoIssueRequest$outboundSchema: z.ZodType<
  UserinfoIssueRequest$Outbound,
  z.ZodTypeDef,
  UserinfoIssueRequest
> = z.object({
  token: z.string(),
  claims: z.string().optional(),
  sub: z.string().optional(),
  claimsForTx: z.string().optional(),
  requestSignature: z.string().optional(),
  headers: z.array(Pair$outboundSchema).optional(),
  verifiedClaimsForTx: z.array(z.string()).optional(),
});

export function userinfoIssueRequestToJSON(
  userinfoIssueRequest: UserinfoIssueRequest,
): string {
  return JSON.stringify(
    UserinfoIssueRequest$outboundSchema.parse(userinfoIssueRequest),
  );
}
